// ============================================================
// ÁLBUM 3 REYES MUNDIAL — Datos reales con IDs exactos
// Total: 584 cromos (1-584) + T-1 a T-48
// ============================================================

// ── ESTADIOS (1-16) ───────────────────────────────────────────
export const ESTADIOS = [
  { id: 1,  section: 'estadios', label: 'Estadio MetLife — Nueva York/NJ',           pais: 'EE.UU.' },
  { id: 2,  section: 'estadios', label: 'Estadio Lincoln Financial — Filadelfia',    pais: 'EE.UU.' },
  { id: 3,  section: 'estadios', label: 'Estadio Mercedes-Benz — Atlanta',           pais: 'EE.UU.' },
  { id: 4,  section: 'estadios', label: 'Estadio Hard Rock — Miami',                 pais: 'EE.UU.' },
  { id: 5,  section: 'estadios', label: "Estadio Levi's — San Francisco",            pais: 'EE.UU.' },
  { id: 6,  section: 'estadios', label: 'Estadio SoFi — Los Ángeles',               pais: 'EE.UU.' },
  { id: 7,  section: 'estadios', label: 'Estadio AT&T — Dallas',                    pais: 'EE.UU.' },
  { id: 8,  section: 'estadios', label: 'Estadio NRG — Houston',                    pais: 'EE.UU.' },
  { id: 9,  section: 'estadios', label: 'Estadio GEHA Arrowhead — Kansas',          pais: 'EE.UU.' },
  { id: 10, section: 'estadios', label: 'Estadio Gillette — Boston',                pais: 'EE.UU.' },
  { id: 11, section: 'estadios', label: 'Estadio Lumen Field — Seattle',            pais: 'EE.UU.' },
  { id: 12, section: 'estadios', label: 'Estadio Akron — Guadalajara',              pais: 'México' },
  { id: 13, section: 'estadios', label: 'Estadio Azteca Banorte — Ciudad de México',pais: 'México' },
  { id: 14, section: 'estadios', label: 'Estadio BBVA — Monterrey',                 pais: 'México' },
  { id: 15, section: 'estadios', label: 'Estadio BMO Field — Toronto',              pais: 'Canadá' },
  { id: 16, section: 'estadios', label: 'Estadio BC Place — Vancouver',             pais: 'Canadá' },
]

// ── PLANTILLAS POR EQUIPO (17-568) ───────────────────────────
export const STICKERS_EQUIPOS = [
  // ── MÉXICO (17-32) ─────────────────────────────────────────
  { id: 17, section: 'grupos', tipo: 'seleccion',    label: 'México — Selección',              pais: 'México',         grupo: 'A' },
  { id: 18, section: 'grupos', tipo: 'dt',           label: 'México — DT J. Aguirre',          pais: 'México',         grupo: 'A' },
  { id: 19, section: 'mvp',    tipo: 'mvp',          label: 'México — MVP L. Malagón',         pais: 'México',         grupo: 'A', isMVP: true, special: true },
  { id: 20, section: 'grupos', tipo: 'defensa',      label: 'México — I. Reyes',               pais: 'México',         grupo: 'A' },
  { id: 21, section: 'grupos', tipo: 'defensa',      label: 'México — J. Vásquez',             pais: 'México',         grupo: 'A' },
  { id: 22, section: 'grupos', tipo: 'defensa',      label: 'México — C. Montes',              pais: 'México',         grupo: 'A' },
  { id: 23, section: 'grupos', tipo: 'defensa',      label: 'México — J. Gallardo',            pais: 'México',         grupo: 'A' },
  { id: 24, section: 'grupos', tipo: 'mediocampista',label: 'México — E. Lira',                pais: 'México',         grupo: 'A' },
  { id: 25, section: 'grupos', tipo: 'mediocampista',label: 'México — G. Mora',                pais: 'México',         grupo: 'A' },
  { id: 26, section: 'grupos', tipo: 'mediocampista',label: 'México — M. Ruiz',                pais: 'México',         grupo: 'A' },
  { id: 27, section: 'grupos', tipo: 'mediocampista',label: 'México — O. Pineda',              pais: 'México',         grupo: 'A' },
  { id: 28, section: 'grupos', tipo: 'mediocampista',label: 'México — E. Álvarez',             pais: 'México',         grupo: 'A' },
  { id: 29, section: 'grupos', tipo: 'delantero',    label: 'México — S. Giménez',             pais: 'México',         grupo: 'A' },
  { id: 30, section: 'grupos', tipo: 'delantero',    label: 'México — J. Quiñones',            pais: 'México',         grupo: 'A' },
  { id: 31, section: 'leyenda',tipo: 'leyenda',      label: 'México — Leyenda R. Jiménez',     pais: 'México',         grupo: 'A', isLeyenda: true, special: true },
  { id: 32, section: 'grupos', tipo: 'delantero',    label: 'México — G. Berterame',           pais: 'México',         grupo: 'A' },

  // ── REP. CHECA (33-48) ─────────────────────────────────────
  { id: 33, section: 'grupos', tipo: 'seleccion',    label: 'Rep. Checa — Selección',          pais: 'Rep. Checa',     grupo: 'A' },
  { id: 34, section: 'grupos', tipo: 'dt',           label: 'Rep. Checa — DT M. Koubek',       pais: 'Rep. Checa',     grupo: 'A' },
  { id: 35, section: 'grupos', tipo: 'arquero',      label: 'Rep. Checa — M. Kovar',           pais: 'Rep. Checa',     grupo: 'A' },
  { id: 36, section: 'grupos', tipo: 'defensa',      label: 'Rep. Checa — J. Zelený',          pais: 'Rep. Checa',     grupo: 'A' },
  { id: 37, section: 'grupos', tipo: 'defensa',      label: 'Rep. Checa — V. Coufal',          pais: 'Rep. Checa',     grupo: 'A' },
  { id: 38, section: 'grupos', tipo: 'defensa',      label: 'Rep. Checa — D. Jurásek',         pais: 'Rep. Checa',     grupo: 'A' },
  { id: 39, section: 'grupos', tipo: 'defensa',      label: 'Rep. Checa — L. Krejčí',          pais: 'Rep. Checa',     grupo: 'A' },
  { id: 40, section: 'grupos', tipo: 'mediocampista',label: 'Rep. Checa — M. Sadílek',         pais: 'Rep. Checa',     grupo: 'A' },
  { id: 41, section: 'grupos', tipo: 'mediocampista',label: 'Rep. Checa — L. Červ',            pais: 'Rep. Checa',     grupo: 'A' },
  { id: 42, section: 'leyenda',tipo: 'leyenda',      label: 'Rep. Checa — Leyenda Souček',     pais: 'Rep. Checa',     grupo: 'A', isLeyenda: true, special: true },
  { id: 43, section: 'grupos', tipo: 'mediocampista',label: 'Rep. Checa — V. Darida',          pais: 'Rep. Checa',     grupo: 'A' },
  { id: 44, section: 'grupos', tipo: 'mediocampista',label: 'Rep. Checa — P. Šulc',            pais: 'Rep. Checa',     grupo: 'A' },
  { id: 45, section: 'grupos', tipo: 'delantero',    label: 'Rep. Checa — V. Cerny',           pais: 'Rep. Checa',     grupo: 'A' },
  { id: 46, section: 'grupos', tipo: 'delantero',    label: 'Rep. Checa — T. Chory',           pais: 'Rep. Checa',     grupo: 'A' },
  { id: 47, section: 'mvp',    tipo: 'mvp',          label: 'Rep. Checa — MVP Schick',         pais: 'Rep. Checa',     grupo: 'A', isMVP: true, special: true },
  { id: 48, section: 'grupos', tipo: 'delantero',    label: 'Rep. Checa — A. Karabec',         pais: 'Rep. Checa',     grupo: 'A' },

  // ── COREA DEL SUR (49-55) ──────────────────────────────────
  { id: 49, section: 'grupos', tipo: 'seleccion',    label: 'Corea del Sur — Selección',       pais: 'Corea del Sur',  grupo: 'A' },
  { id: 50, section: 'grupos', tipo: 'arquero',      label: 'Corea del Sur — Hyeon-Woo Jo',    pais: 'Corea del Sur',  grupo: 'A' },
  { id: 51, section: 'grupos', tipo: 'defensa',      label: 'Corea del Sur — Young-Woo Seol',  pais: 'Corea del Sur',  grupo: 'A' },
  { id: 52, section: 'grupos', tipo: 'defensa',      label: 'Corea del Sur — Min-Jae Kim',     pais: 'Corea del Sur',  grupo: 'A' },
  { id: 53, section: 'mvp',    tipo: 'mvp',          label: 'Corea del Sur — MVP Kang-In Lee', pais: 'Corea del Sur',  grupo: 'A', isMVP: true, special: true },
  { id: 54, section: 'grupos', tipo: 'delantero',    label: 'Corea del Sur — Hee-Chan Hwang',  pais: 'Corea del Sur',  grupo: 'A' },
  { id: 55, section: 'leyenda',tipo: 'leyenda',      label: 'Corea del Sur — Leyenda Heung-Min Son', pais: 'Corea del Sur', grupo: 'A', isLeyenda: true, special: true },

  // ── SUDÁFRICA (56-62) ──────────────────────────────────────
  { id: 56, section: 'grupos', tipo: 'seleccion',    label: 'Sudáfrica — Selección',           pais: 'Sudáfrica',      grupo: 'A' },
  { id: 57, section: 'leyenda',tipo: 'leyenda',      label: 'Sudáfrica — Leyenda R. Williams', pais: 'Sudáfrica',      grupo: 'A', isLeyenda: true, special: true },
  { id: 58, section: 'grupos', tipo: 'defensa',      label: 'Sudáfrica — K. Mudau',            pais: 'Sudáfrica',      grupo: 'A' },
  { id: 59, section: 'grupos', tipo: 'defensa',      label: 'Sudáfrica — S. Ngezana',          pais: 'Sudáfrica',      grupo: 'A' },
  { id: 60, section: 'grupos', tipo: 'mediocampista',label: 'Sudáfrica — T. Mokoena',          pais: 'Sudáfrica',      grupo: 'A' },
  { id: 61, section: 'grupos', tipo: 'delantero',    label: 'Sudáfrica — O. Appollis',         pais: 'Sudáfrica',      grupo: 'A' },
  { id: 62, section: 'mvp',    tipo: 'mvp',          label: 'Sudáfrica — MVP L. Foster',       pais: 'Sudáfrica',      grupo: 'A', isMVP: true, special: true },

  // ── CANADÁ (63-78) ─────────────────────────────────────────
  { id: 63, section: 'grupos', tipo: 'seleccion',    label: 'Canadá — Selección',              pais: 'Canadá',         grupo: 'B' },
  { id: 64, section: 'grupos', tipo: 'dt',           label: 'Canadá — DT J. Marsch',           pais: 'Canadá',         grupo: 'B' },
  { id: 65, section: 'grupos', tipo: 'arquero',      label: 'Canadá — D. St. Clair',           pais: 'Canadá',         grupo: 'B' },
  { id: 66, section: 'grupos', tipo: 'defensa',      label: 'Canadá — M. Bombito',             pais: 'Canadá',         grupo: 'B' },
  { id: 67, section: 'grupos', tipo: 'defensa',      label: 'Canadá — R. Laryea',              pais: 'Canadá',         grupo: 'B' },
  { id: 68, section: 'grupos', tipo: 'defensa',      label: 'Canadá — D. Cornelius',           pais: 'Canadá',         grupo: 'B' },
  { id: 69, section: 'grupos', tipo: 'defensa',      label: 'Canadá — A. Johnston',            pais: 'Canadá',         grupo: 'B' },
  { id: 70, section: 'leyenda',tipo: 'leyenda',      label: 'Canadá — Leyenda S. Eustaquio',   pais: 'Canadá',         grupo: 'B', isLeyenda: true, special: true },
  { id: 71, section: 'grupos', tipo: 'mediocampista',label: 'Canadá — I. Koné',                pais: 'Canadá',         grupo: 'B' },
  { id: 72, section: 'mvp',    tipo: 'mvp',          label: 'Canadá — MVP A. Davies',          pais: 'Canadá',         grupo: 'B', isMVP: true, special: true },
  { id: 73, section: 'grupos', tipo: 'mediocampista',label: 'Canadá — A. Ahmed',               pais: 'Canadá',         grupo: 'B' },
  { id: 74, section: 'grupos', tipo: 'mediocampista',label: 'Canadá — T. Buchanan',            pais: 'Canadá',         grupo: 'B' },
  { id: 75, section: 'grupos', tipo: 'delantero',    label: 'Canadá — T. Oluwaseyi',           pais: 'Canadá',         grupo: 'B' },
  { id: 76, section: 'grupos', tipo: 'delantero',    label: 'Canadá — J. David',               pais: 'Canadá',         grupo: 'B' },
  { id: 77, section: 'grupos', tipo: 'delantero',    label: 'Canadá — C. Larin',               pais: 'Canadá',         grupo: 'B' },
  { id: 78, section: 'grupos', tipo: 'delantero',    label: 'Canadá — J. Shaffelburg',         pais: 'Canadá',         grupo: 'B' },

  // ── BOSNIA Y HERZEGOVINA (79-94) ───────────────────────────
  { id: 79, section: 'grupos', tipo: 'seleccion',    label: 'Bosnia y Herz. — Selección',      pais: 'Bosnia y Herz.', grupo: 'B' },
  { id: 80, section: 'grupos', tipo: 'dt',           label: 'Bosnia y Herz. — DT S. Barbarez', pais: 'Bosnia y Herz.', grupo: 'B' },
  { id: 81, section: 'grupos', tipo: 'arquero',      label: 'Bosnia y Herz. — N. Vasilj',      pais: 'Bosnia y Herz.', grupo: 'B' },
  { id: 82, section: 'grupos', tipo: 'defensa',      label: 'Bosnia y Herz. — A. Barisic',     pais: 'Bosnia y Herz.', grupo: 'B' },
  { id: 83, section: 'mvp',    tipo: 'mvp',          label: 'Bosnia y Herz. — MVP A. Dedić',   pais: 'Bosnia y Herz.', grupo: 'B', isMVP: true, special: true },
  { id: 84, section: 'grupos', tipo: 'defensa',      label: 'Bosnia y Herz. — A. Malic',       pais: 'Bosnia y Herz.', grupo: 'B' },
  { id: 85, section: 'grupos', tipo: 'defensa',      label: 'Bosnia y Herz. — T. Muharemović', pais: 'Bosnia y Herz.', grupo: 'B' },
  { id: 86, section: 'grupos', tipo: 'mediocampista',label: 'Bosnia y Herz. — B. Tahirovic',   pais: 'Bosnia y Herz.', grupo: 'B' },
  { id: 87, section: 'grupos', tipo: 'mediocampista',label: 'Bosnia y Herz. — A. Gigovic',     pais: 'Bosnia y Herz.', grupo: 'B' },
  { id: 88, section: 'grupos', tipo: 'mediocampista',label: 'Bosnia y Herz. — I. Sunjic',      pais: 'Bosnia y Herz.', grupo: 'B' },
  { id: 89, section: 'grupos', tipo: 'mediocampista',label: 'Bosnia y Herz. — D. Burnic',      pais: 'Bosnia y Herz.', grupo: 'B' },
  { id: 90, section: 'grupos', tipo: 'mediocampista',label: 'Bosnia y Herz. — A. Hadziahmetovic', pais: 'Bosnia y Herz.', grupo: 'B' },
  { id: 91, section: 'leyenda',tipo: 'leyenda',      label: 'Bosnia y Herz. — Leyenda E. Dzeko', pais: 'Bosnia y Herz.', grupo: 'B', isLeyenda: true, special: true },
  { id: 92, section: 'grupos', tipo: 'delantero',    label: 'Bosnia y Herz. — A. Memic',       pais: 'Bosnia y Herz.', grupo: 'B' },
  { id: 93, section: 'grupos', tipo: 'delantero',    label: 'Bosnia y Herz. — E. Demirovic',   pais: 'Bosnia y Herz.', grupo: 'B' },
  { id: 94, section: 'grupos', tipo: 'delantero',    label: 'Bosnia y Herz. — S. Bazdar',      pais: 'Bosnia y Herz.', grupo: 'B' },

  // ── SUIZA (95-101) ─────────────────────────────────────────
  { id: 95,  section: 'grupos', tipo: 'seleccion',   label: 'Suiza — Selección',               pais: 'Suiza',          grupo: 'B' },
  { id: 96,  section: 'grupos', tipo: 'arquero',     label: 'Suiza — G. Kobel',                pais: 'Suiza',          grupo: 'B' },
  { id: 97,  section: 'grupos', tipo: 'defensa',     label: 'Suiza — R. Rodríguez',            pais: 'Suiza',          grupo: 'B' },
  { id: 98,  section: 'grupos', tipo: 'defensa',     label: 'Suiza — M. Akanji',               pais: 'Suiza',          grupo: 'B' },
  { id: 99,  section: 'leyenda',tipo: 'leyenda',     label: 'Suiza — Leyenda G. Xhaka',        pais: 'Suiza',          grupo: 'B', isLeyenda: true, special: true },
  { id: 100, section: 'grupos', tipo: 'delantero',   label: 'Suiza — B. Embolo',               pais: 'Suiza',          grupo: 'B' },
  { id: 101, section: 'mvp',    tipo: 'mvp',         label: 'Suiza — MVP D. Ndoye',            pais: 'Suiza',          grupo: 'B', isMVP: true, special: true },

  // ── CATAR (102-108) ────────────────────────────────────────
  { id: 102, section: 'grupos', tipo: 'seleccion',   label: 'Catar — Selección',               pais: 'Catar',          grupo: 'B' },
  { id: 103, section: 'grupos', tipo: 'arquero',     label: 'Catar — M. Barsham',              pais: 'Catar',          grupo: 'B' },
  { id: 104, section: 'grupos', tipo: 'defensa',     label: 'Catar — H. Al-Amin',              pais: 'Catar',          grupo: 'B' },
  { id: 105, section: 'leyenda',tipo: 'leyenda',     label: 'Catar — Leyenda P. Miguel',       pais: 'Catar',          grupo: 'B', isLeyenda: true, special: true },
  { id: 106, section: 'grupos', tipo: 'mediocampista',label: 'Catar — A. Fathi',               pais: 'Catar',          grupo: 'B' },
  { id: 107, section: 'mvp',    tipo: 'mvp',         label: 'Catar — MVP A. Afif',             pais: 'Catar',          grupo: 'B', isMVP: true, special: true },
  { id: 108, section: 'grupos', tipo: 'delantero',   label: 'Catar — E. Junior',               pais: 'Catar',          grupo: 'B' },

  // ── BRASIL (109-124) ───────────────────────────────────────
  { id: 109, section: 'grupos', tipo: 'seleccion',   label: 'Brasil — Selección',              pais: 'Brasil',         grupo: 'C' },
  { id: 110, section: 'grupos', tipo: 'dt',          label: 'Brasil — DT C. Ancelotti',        pais: 'Brasil',         grupo: 'C' },
  { id: 111, section: 'leyenda',tipo: 'leyenda',     label: 'Brasil — Leyenda Alisson',        pais: 'Brasil',         grupo: 'C', isLeyenda: true, special: true },
  { id: 112, section: 'grupos', tipo: 'defensa',     label: 'Brasil — Marquinhos',             pais: 'Brasil',         grupo: 'C' },
  { id: 113, section: 'grupos', tipo: 'defensa',     label: 'Brasil — G. Magalhães',           pais: 'Brasil',         grupo: 'C' },
  { id: 114, section: 'grupos', tipo: 'defensa',     label: 'Brasil — E. Militão',             pais: 'Brasil',         grupo: 'C' },
  { id: 115, section: 'grupos', tipo: 'defensa',     label: 'Brasil — Wesley',                 pais: 'Brasil',         grupo: 'C' },
  { id: 116, section: 'grupos', tipo: 'mediocampista',label: 'Brasil — Casemiro',              pais: 'Brasil',         grupo: 'C' },
  { id: 117, section: 'grupos', tipo: 'mediocampista',label: 'Brasil — B. Guimarães',          pais: 'Brasil',         grupo: 'C' },
  { id: 118, section: 'grupos', tipo: 'mediocampista',label: 'Brasil — L. Paquetá',            pais: 'Brasil',         grupo: 'C' },
  { id: 119, section: 'grupos', tipo: 'mediocampista',label: 'Brasil — Raphinha',              pais: 'Brasil',         grupo: 'C' },
  { id: 120, section: 'grupos', tipo: 'delantero',   label: 'Brasil — M. Cunha',               pais: 'Brasil',         grupo: 'C' },
  { id: 121, section: 'grupos', tipo: 'delantero',   label: 'Brasil — Estêvão',                pais: 'Brasil',         grupo: 'C' },
  { id: 122, section: 'grupos', tipo: 'delantero',   label: 'Brasil — Endrick',                pais: 'Brasil',         grupo: 'C' },
  { id: 123, section: 'grupos', tipo: 'delantero',   label: 'Brasil — J. Pedro / Neymar Jr.',  pais: 'Brasil',         grupo: 'C' },
  { id: 124, section: 'mvp',    tipo: 'mvp',         label: 'Brasil — MVP Vinicius Jr.',       pais: 'Brasil',         grupo: 'C', isMVP: true, special: true },

  // ── MARRUECOS (125-140) ────────────────────────────────────
  { id: 125, section: 'grupos', tipo: 'seleccion',   label: 'Marruecos — Selección',           pais: 'Marruecos',      grupo: 'C' },
  { id: 126, section: 'grupos', tipo: 'dt',          label: 'Marruecos — DT W. Regragui',      pais: 'Marruecos',      grupo: 'C' },
  { id: 127, section: 'leyenda',tipo: 'leyenda',     label: 'Marruecos — Leyenda Y. Bounou',   pais: 'Marruecos',      grupo: 'C', isLeyenda: true, special: true },
  { id: 128, section: 'grupos', tipo: 'defensa',     label: 'Marruecos — S. Amrabat',          pais: 'Marruecos',      grupo: 'C' },
  { id: 129, section: 'grupos', tipo: 'defensa',     label: 'Marruecos — N. Aguerd',           pais: 'Marruecos',      grupo: 'C' },
  { id: 130, section: 'grupos', tipo: 'defensa',     label: 'Marruecos — N. Mazraoui',         pais: 'Marruecos',      grupo: 'C' },
  { id: 131, section: 'mvp',    tipo: 'mvp',         label: 'Marruecos — MVP A. Hakimi',       pais: 'Marruecos',      grupo: 'C', isMVP: true, special: true },
  { id: 132, section: 'grupos', tipo: 'mediocampista',label: 'Marruecos — B. El Khannouss',    pais: 'Marruecos',      grupo: 'C' },
  { id: 133, section: 'grupos', tipo: 'mediocampista',label: 'Marruecos — N. El Aynaoui',      pais: 'Marruecos',      grupo: 'C' },
  { id: 134, section: 'grupos', tipo: 'mediocampista',label: 'Marruecos — I. Saibari',         pais: 'Marruecos',      grupo: 'C' },
  { id: 135, section: 'grupos', tipo: 'mediocampista',label: 'Marruecos — B. Díaz',            pais: 'Marruecos',      grupo: 'C' },
  { id: 136, section: 'grupos', tipo: 'mediocampista',label: 'Marruecos — A. Ounahi',          pais: 'Marruecos',      grupo: 'C' },
  { id: 137, section: 'grupos', tipo: 'delantero',   label: 'Marruecos — Y. En-Nesyri',        pais: 'Marruecos',      grupo: 'C' },
  { id: 138, section: 'grupos', tipo: 'delantero',   label: 'Marruecos — A. El Kaabi',         pais: 'Marruecos',      grupo: 'C' },
  { id: 139, section: 'grupos', tipo: 'delantero',   label: 'Marruecos — E. Ben Seghir',       pais: 'Marruecos',      grupo: 'C' },
  { id: 140, section: 'grupos', tipo: 'delantero',   label: 'Marruecos — A. Ezzalzouli',       pais: 'Marruecos',      grupo: 'C' },

  // ── ESCOCIA (141-147) ──────────────────────────────────────
  { id: 141, section: 'grupos', tipo: 'seleccion',   label: 'Escocia — Selección',             pais: 'Escocia',        grupo: 'C' },
  { id: 142, section: 'grupos', tipo: 'arquero',     label: 'Escocia — A. Gunn',               pais: 'Escocia',        grupo: 'C' },
  { id: 143, section: 'leyenda',tipo: 'leyenda',     label: 'Escocia — Leyenda J. McGinn',     pais: 'Escocia',        grupo: 'C', isLeyenda: true, special: true },
  { id: 144, section: 'grupos', tipo: 'defensa',     label: 'Escocia — A. Robertson',          pais: 'Escocia',        grupo: 'C' },
  { id: 145, section: 'mvp',    tipo: 'mvp',         label: 'Escocia — MVP S. McTominay',      pais: 'Escocia',        grupo: 'C', isMVP: true, special: true },
  { id: 146, section: 'grupos', tipo: 'delantero',   label: 'Escocia — B. Gannon-Doak',        pais: 'Escocia',        grupo: 'C' },
  { id: 147, section: 'grupos', tipo: 'delantero',   label: 'Escocia — C. Adams',              pais: 'Escocia',        grupo: 'C' },

  // ── HAITÍ (148-154) ────────────────────────────────────────
  { id: 148, section: 'grupos', tipo: 'seleccion',   label: 'Haití — Selección',               pais: 'Haití',          grupo: 'C' },
  { id: 149, section: 'leyenda',tipo: 'leyenda',     label: 'Haití — Leyenda J. Placide',      pais: 'Haití',          grupo: 'C', isLeyenda: true, special: true },
  { id: 150, section: 'grupos', tipo: 'defensa',     label: 'Haití — C. Arcus',                pais: 'Haití',          grupo: 'C' },
  { id: 151, section: 'grupos', tipo: 'defensa',     label: 'Haití — R. Adé',                  pais: 'Haití',          grupo: 'C' },
  { id: 152, section: 'mvp',    tipo: 'mvp',         label: 'Haití — MVP J. Bellegarde',       pais: 'Haití',          grupo: 'C', isMVP: true, special: true },
  { id: 153, section: 'grupos', tipo: 'delantero',   label: 'Haití — D. Nazon',                pais: 'Haití',          grupo: 'C' },
  { id: 154, section: 'grupos', tipo: 'delantero',   label: 'Haití — F. Pierrot',              pais: 'Haití',          grupo: 'C' },

  // ── EE.UU. (155-170) ───────────────────────────────────────
  { id: 155, section: 'grupos', tipo: 'seleccion',   label: 'EE.UU. — Selección',              pais: 'EE.UU.',         grupo: 'D' },
  { id: 156, section: 'grupos', tipo: 'dt',          label: 'EE.UU. — DT M. Pochettino',       pais: 'EE.UU.',         grupo: 'D' },
  { id: 157, section: 'grupos', tipo: 'arquero',     label: 'EE.UU. — M. Freese',              pais: 'EE.UU.',         grupo: 'D' },
  { id: 158, section: 'leyenda',tipo: 'leyenda',     label: 'EE.UU. — Leyenda T. Ream',        pais: 'EE.UU.',         grupo: 'D', isLeyenda: true, special: true },
  { id: 159, section: 'grupos', tipo: 'defensa',     label: 'EE.UU. — C. Richards',            pais: 'EE.UU.',         grupo: 'D' },
  { id: 160, section: 'grupos', tipo: 'defensa',     label: 'EE.UU. — A. Robinson',            pais: 'EE.UU.',         grupo: 'D' },
  { id: 161, section: 'grupos', tipo: 'defensa',     label: 'EE.UU. — A. Freeman',             pais: 'EE.UU.',         grupo: 'D' },
  { id: 162, section: 'grupos', tipo: 'mediocampista',label: 'EE.UU. — D. Luna',               pais: 'EE.UU.',         grupo: 'D' },
  { id: 163, section: 'grupos', tipo: 'mediocampista',label: 'EE.UU. — M. Tillman',            pais: 'EE.UU.',         grupo: 'D' },
  { id: 164, section: 'grupos', tipo: 'mediocampista',label: 'EE.UU. — L. de la Torre',        pais: 'EE.UU.',         grupo: 'D' },
  { id: 165, section: 'grupos', tipo: 'mediocampista',label: 'EE.UU. — T. Weah',               pais: 'EE.UU.',         grupo: 'D' },
  { id: 166, section: 'grupos', tipo: 'mediocampista',label: 'EE.UU. — W. McKennie',           pais: 'EE.UU.',         grupo: 'D' },
  { id: 167, section: 'grupos', tipo: 'delantero',   label: 'EE.UU. — F. Balogun',             pais: 'EE.UU.',         grupo: 'D' },
  { id: 168, section: 'grupos', tipo: 'delantero',   label: 'EE.UU. — M. Arfsten',             pais: 'EE.UU.',         grupo: 'D' },
  { id: 169, section: 'mvp',    tipo: 'mvp',         label: 'EE.UU. — MVP C. Pulisic',         pais: 'EE.UU.',         grupo: 'D', isMVP: true, special: true },
  { id: 170, section: 'grupos', tipo: 'delantero',   label: 'EE.UU. — P. Agyemang',            pais: 'EE.UU.',         grupo: 'D' },

  // ── PARAGUAY (171-186) ─────────────────────────────────────
  { id: 171, section: 'grupos', tipo: 'seleccion',   label: 'Paraguay — Selección',            pais: 'Paraguay',       grupo: 'D' },
  { id: 172, section: 'grupos', tipo: 'dt',          label: 'Paraguay — DT G. Alfaro',         pais: 'Paraguay',       grupo: 'D' },
  { id: 173, section: 'grupos', tipo: 'arquero',     label: 'Paraguay — R. Fernández',         pais: 'Paraguay',       grupo: 'D' },
  { id: 174, section: 'grupos', tipo: 'defensa',     label: 'Paraguay — J. Alonso',            pais: 'Paraguay',       grupo: 'D' },
  { id: 175, section: 'leyenda',tipo: 'leyenda',     label: 'Paraguay — Leyenda G. Gómez',     pais: 'Paraguay',       grupo: 'D', isLeyenda: true, special: true },
  { id: 176, section: 'grupos', tipo: 'defensa',     label: 'Paraguay — O. Alderete',          pais: 'Paraguay',       grupo: 'D' },
  { id: 177, section: 'grupos', tipo: 'defensa',     label: 'Paraguay — J. Caceres',           pais: 'Paraguay',       grupo: 'D' },
  { id: 178, section: 'grupos', tipo: 'mediocampista',label: 'Paraguay — D. Gómez',            pais: 'Paraguay',       grupo: 'D' },
  { id: 179, section: 'grupos', tipo: 'mediocampista',label: 'Paraguay — A. Cubas',            pais: 'Paraguay',       grupo: 'D' },
  { id: 180, section: 'grupos', tipo: 'mediocampista',label: 'Paraguay — D. Bobadilla',        pais: 'Paraguay',       grupo: 'D' },
  { id: 181, section: 'grupos', tipo: 'mediocampista',label: 'Paraguay — M. Galarza',          pais: 'Paraguay',       grupo: 'D' },
  { id: 182, section: 'grupos', tipo: 'mediocampista',label: 'Paraguay — M. Villasanti',       pais: 'Paraguay',       grupo: 'D' },
  { id: 183, section: 'grupos', tipo: 'delantero',   label: 'Paraguay — A. Sanabria',          pais: 'Paraguay',       grupo: 'D' },
  { id: 184, section: 'mvp',    tipo: 'mvp',         label: 'Paraguay — MVP M. Almirón',       pais: 'Paraguay',       grupo: 'D', isMVP: true, special: true },
  { id: 185, section: 'grupos', tipo: 'delantero',   label: 'Paraguay — J. Enciso',            pais: 'Paraguay',       grupo: 'D' },
  { id: 186, section: 'grupos', tipo: 'delantero',   label: 'Paraguay — R. Sosa',              pais: 'Paraguay',       grupo: 'D' },

  // ── AUSTRALIA (187-193) ────────────────────────────────────
  { id: 187, section: 'grupos', tipo: 'seleccion',   label: 'Australia — Selección',           pais: 'Australia',      grupo: 'D' },
  { id: 188, section: 'leyenda',tipo: 'leyenda',     label: 'Australia — Leyenda M. Ryan',     pais: 'Australia',      grupo: 'D', isLeyenda: true, special: true },
  { id: 189, section: 'grupos', tipo: 'defensa',     label: 'Australia — C. Burgess',          pais: 'Australia',      grupo: 'D' },
  { id: 190, section: 'grupos', tipo: 'defensa',     label: 'Australia — L. Miller',           pais: 'Australia',      grupo: 'D' },
  { id: 191, section: 'grupos', tipo: 'mediocampista',label: 'Australia — C. Metcalfe',        pais: 'Australia',      grupo: 'D' },
  { id: 192, section: 'mvp',    tipo: 'mvp',         label: 'Australia — MVP N. Irankunda',    pais: 'Australia',      grupo: 'D', isMVP: true, special: true },
  { id: 193, section: 'grupos', tipo: 'delantero',   label: 'Australia — M. Touré',            pais: 'Australia',      grupo: 'D' },

  // ── TURQUÍA (194-200) ──────────────────────────────────────
  { id: 194, section: 'grupos', tipo: 'seleccion',   label: 'Turquía — Selección',             pais: 'Turquía',        grupo: 'D' },
  { id: 195, section: 'grupos', tipo: 'arquero',     label: 'Turquía — U. Çakir',              pais: 'Turquía',        grupo: 'D' },
  { id: 196, section: 'grupos', tipo: 'defensa',     label: 'Turquía — A. Bardakci',           pais: 'Turquía',        grupo: 'D' },
  { id: 197, section: 'grupos', tipo: 'defensa',     label: 'Turquía — M. Demiral',            pais: 'Turquía',        grupo: 'D' },
  { id: 198, section: 'leyenda',tipo: 'leyenda',     label: 'Turquía — Leyenda H. Çalhanoglu', pais: 'Turquía',        grupo: 'D', isLeyenda: true, special: true },
  { id: 199, section: 'grupos', tipo: 'delantero',   label: 'Turquía — K. Yildiz',             pais: 'Turquía',        grupo: 'D' },
  { id: 200, section: 'mvp',    tipo: 'mvp',         label: 'Turquía — MVP A. Güler',          pais: 'Turquía',        grupo: 'D', isMVP: true, special: true },

  // ── ALEMANIA (201-216) ─────────────────────────────────────
  { id: 201, section: 'grupos', tipo: 'seleccion',   label: 'Alemania — Selección',            pais: 'Alemania',       grupo: 'E' },
  { id: 202, section: 'grupos', tipo: 'dt',          label: 'Alemania — DT J. Nagelsmann',     pais: 'Alemania',       grupo: 'E' },
  { id: 203, section: 'leyenda',tipo: 'leyenda',     label: 'Alemania — Leyenda M. Ter Stegen',pais: 'Alemania',       grupo: 'E', isLeyenda: true, special: true },
  { id: 204, section: 'grupos', tipo: 'defensa',     label: 'Alemania — N. Schlotterbeck',     pais: 'Alemania',       grupo: 'E' },
  { id: 205, section: 'grupos', tipo: 'defensa',     label: 'Alemania — J. Tah',               pais: 'Alemania',       grupo: 'E' },
  { id: 206, section: 'grupos', tipo: 'defensa',     label: 'Alemania — D. Raum',              pais: 'Alemania',       grupo: 'E' },
  { id: 207, section: 'grupos', tipo: 'defensa',     label: 'Alemania — A. Rüdiger',           pais: 'Alemania',       grupo: 'E' },
  { id: 208, section: 'grupos', tipo: 'mediocampista',label: 'Alemania — J. Kimmich',          pais: 'Alemania',       grupo: 'E' },
  { id: 209, section: 'mvp',    tipo: 'mvp',         label: 'Alemania — MVP F. Wirtz',         pais: 'Alemania',       grupo: 'E', isMVP: true, special: true },
  { id: 210, section: 'grupos', tipo: 'mediocampista',label: 'Alemania — L. Goretzka',         pais: 'Alemania',       grupo: 'E' },
  { id: 211, section: 'grupos', tipo: 'mediocampista',label: 'Alemania — A. Pavlovic',         pais: 'Alemania',       grupo: 'E' },
  { id: 212, section: 'grupos', tipo: 'mediocampista',label: 'Alemania — J. Musiala',          pais: 'Alemania',       grupo: 'E' },
  { id: 213, section: 'grupos', tipo: 'delantero',   label: 'Alemania — K. Adeyemi',           pais: 'Alemania',       grupo: 'E' },
  { id: 214, section: 'grupos', tipo: 'delantero',   label: 'Alemania — N. Woltemade',         pais: 'Alemania',       grupo: 'E' },
  { id: 215, section: 'grupos', tipo: 'delantero',   label: 'Alemania — L. Sané',              pais: 'Alemania',       grupo: 'E' },
  { id: 216, section: 'grupos', tipo: 'delantero',   label: 'Alemania — S. Gnabry',            pais: 'Alemania',       grupo: 'E' },

  // ── ECUADOR (217-232) ──────────────────────────────────────
  { id: 217, section: 'grupos', tipo: 'seleccion',   label: 'Ecuador — Selección',             pais: 'Ecuador',        grupo: 'E' },
  { id: 218, section: 'grupos', tipo: 'dt',          label: 'Ecuador — DT S. Beccacece',       pais: 'Ecuador',        grupo: 'E' },
  { id: 219, section: 'grupos', tipo: 'arquero',     label: 'Ecuador — H. Galíndez',           pais: 'Ecuador',        grupo: 'E' },
  { id: 220, section: 'grupos', tipo: 'defensa',     label: 'Ecuador — A. Preciado',           pais: 'Ecuador',        grupo: 'E' },
  { id: 221, section: 'grupos', tipo: 'defensa',     label: 'Ecuador — J. Ordóñez',            pais: 'Ecuador',        grupo: 'E' },
  { id: 222, section: 'grupos', tipo: 'defensa',     label: 'Ecuador — P. Hincapié',           pais: 'Ecuador',        grupo: 'E' },
  { id: 223, section: 'grupos', tipo: 'defensa',     label: 'Ecuador — W. Pacho',              pais: 'Ecuador',        grupo: 'E' },
  { id: 224, section: 'leyenda',tipo: 'leyenda',     label: 'Ecuador — Leyenda M. Caicedo',    pais: 'Ecuador',        grupo: 'E', isLeyenda: true, special: true },
  { id: 225, section: 'grupos', tipo: 'mediocampista',label: 'Ecuador — P. Vite',              pais: 'Ecuador',        grupo: 'E' },
  { id: 226, section: 'grupos', tipo: 'mediocampista',label: 'Ecuador — A. Franco',            pais: 'Ecuador',        grupo: 'E' },
  { id: 227, section: 'grupos', tipo: 'mediocampista',label: 'Ecuador — P. Estupiñán',         pais: 'Ecuador',        grupo: 'E' },
  { id: 228, section: 'grupos', tipo: 'mediocampista',label: 'Ecuador — N. Angulo',            pais: 'Ecuador',        grupo: 'E' },
  { id: 229, section: 'mvp',    tipo: 'mvp',         label: 'Ecuador — MVP E. Valencia',       pais: 'Ecuador',        grupo: 'E', isMVP: true, special: true },
  { id: 230, section: 'grupos', tipo: 'delantero',   label: 'Ecuador — J. Yeboah',             pais: 'Ecuador',        grupo: 'E' },
  { id: 231, section: 'grupos', tipo: 'delantero',   label: 'Ecuador — K. Rodríguez',          pais: 'Ecuador',        grupo: 'E' },
  { id: 232, section: 'grupos', tipo: 'delantero',   label: 'Ecuador — G. Plata',              pais: 'Ecuador',        grupo: 'E' },

  // ── COSTA DE MARFIL (233-239) ──────────────────────────────
  { id: 233, section: 'grupos', tipo: 'seleccion',   label: 'Costa de Marfil — Selección',     pais: 'Costa de Marfil',grupo: 'E' },
  { id: 234, section: 'grupos', tipo: 'arquero',     label: 'Costa de Marfil — Y. Fofana',     pais: 'Costa de Marfil',grupo: 'E' },
  { id: 235, section: 'grupos', tipo: 'defensa',     label: 'Costa de Marfil — E. Ndicka',     pais: 'Costa de Marfil',grupo: 'E' },
  { id: 236, section: 'grupos', tipo: 'defensa',     label: 'Costa de Marfil — G. Konan',      pais: 'Costa de Marfil',grupo: 'E' },
  { id: 237, section: 'grupos', tipo: 'mediocampista',label: 'Costa de Marfil — F. Kessié',    pais: 'Costa de Marfil',grupo: 'E' },
  { id: 238, section: 'mvp',    tipo: 'mvp',         label: 'Costa de Marfil — MVP A. Diallo', pais: 'Costa de Marfil',grupo: 'E', isMVP: true, special: true },
  { id: 239, section: 'leyenda',tipo: 'leyenda',     label: 'Costa de Marfil — Leyenda W. Zaha',pais: 'Costa de Marfil',grupo: 'E', isLeyenda: true, special: true },

  // ── CURAZAO (240-246) ──────────────────────────────────────
  { id: 240, section: 'grupos', tipo: 'seleccion',   label: 'Curazao — Selección',             pais: 'Curazao',        grupo: 'E' },
  { id: 241, section: 'leyenda',tipo: 'leyenda',     label: 'Curazao — Leyenda E. Room',       pais: 'Curazao',        grupo: 'E', isLeyenda: true, special: true },
  { id: 242, section: 'grupos', tipo: 'defensa',     label: 'Curazao — L. Comenencia',         pais: 'Curazao',        grupo: 'E' },
  { id: 243, section: 'grupos', tipo: 'defensa',     label: 'Curazao — S. Floranus',           pais: 'Curazao',        grupo: 'E' },
  { id: 244, section: 'mvp',    tipo: 'mvp',         label: 'Curazao — MVP L. Bacuna',         pais: 'Curazao',        grupo: 'E', isMVP: true, special: true },
  { id: 245, section: 'grupos', tipo: 'delantero',   label: 'Curazao — J. Margaritha',         pais: 'Curazao',        grupo: 'E' },
  { id: 246, section: 'grupos', tipo: 'delantero',   label: 'Curazao — K. Gorré',              pais: 'Curazao',        grupo: 'E' },

  // ── PAÍSES BAJOS (247-262) ─────────────────────────────────
  { id: 247, section: 'grupos', tipo: 'seleccion',   label: 'Países Bajos — Selección',        pais: 'Países Bajos',   grupo: 'F' },
  { id: 248, section: 'grupos', tipo: 'dt',          label: 'Países Bajos — DT R. Koeman',     pais: 'Países Bajos',   grupo: 'F' },
  { id: 249, section: 'grupos', tipo: 'arquero',     label: 'Países Bajos — B. Verbruggen',    pais: 'Países Bajos',   grupo: 'F' },
  { id: 250, section: 'grupos', tipo: 'defensa',     label: 'Países Bajos — D. Dumfries',      pais: 'Países Bajos',   grupo: 'F' },
  { id: 251, section: 'leyenda',tipo: 'leyenda',     label: 'Países Bajos — Leyenda V. Van Dijk',pais: 'Países Bajos', grupo: 'F', isLeyenda: true, special: true },
  { id: 252, section: 'grupos', tipo: 'defensa',     label: 'Países Bajos — M. Van De Ven',    pais: 'Países Bajos',   grupo: 'F' },
  { id: 253, section: 'grupos', tipo: 'defensa',     label: 'Países Bajos — N. Aké',           pais: 'Países Bajos',   grupo: 'F' },
  { id: 254, section: 'grupos', tipo: 'mediocampista',label: 'Países Bajos — F. de Jong',      pais: 'Países Bajos',   grupo: 'F' },
  { id: 255, section: 'grupos', tipo: 'mediocampista',label: 'Países Bajos — T. Reijnders',    pais: 'Países Bajos',   grupo: 'F' },
  { id: 256, section: 'grupos', tipo: 'mediocampista',label: 'Países Bajos — R. Gravenberch',  pais: 'Países Bajos',   grupo: 'F' },
  { id: 257, section: 'grupos', tipo: 'mediocampista',label: 'Países Bajos — J. Frimpong',     pais: 'Países Bajos',   grupo: 'F' },
  { id: 258, section: 'grupos', tipo: 'mediocampista',label: 'Países Bajos — X. Simons',       pais: 'Países Bajos',   grupo: 'F' },
  { id: 259, section: 'grupos', tipo: 'delantero',   label: 'Países Bajos — C. Gakpo',         pais: 'Países Bajos',   grupo: 'F' },
  { id: 260, section: 'mvp',    tipo: 'mvp',         label: 'Países Bajos — MVP M. Depay',     pais: 'Países Bajos',   grupo: 'F', isMVP: true, special: true },
  { id: 261, section: 'grupos', tipo: 'delantero',   label: 'Países Bajos — D. Malen',         pais: 'Países Bajos',   grupo: 'F' },
  { id: 262, section: 'grupos', tipo: 'delantero',   label: 'Países Bajos — J. Kluivert',      pais: 'Países Bajos',   grupo: 'F' },

  // ── SUECIA (263-278) ───────────────────────────────────────
  { id: 263, section: 'grupos', tipo: 'seleccion',   label: 'Suecia — Selección',              pais: 'Suecia',         grupo: 'F' },
  { id: 264, section: 'grupos', tipo: 'dt',          label: 'Suecia — DT G. Potter',           pais: 'Suecia',         grupo: 'F' },
  { id: 265, section: 'grupos', tipo: 'arquero',     label: 'Suecia — K. Nordfeldt',           pais: 'Suecia',         grupo: 'F' },
  { id: 266, section: 'grupos', tipo: 'defensa',     label: 'Suecia — I. Hien',                pais: 'Suecia',         grupo: 'F' },
  { id: 267, section: 'leyenda',tipo: 'leyenda',     label: 'Suecia — Leyenda V. Lindelöf',    pais: 'Suecia',         grupo: 'F', isLeyenda: true, special: true },
  { id: 268, section: 'grupos', tipo: 'defensa',     label: 'Suecia — G. Gudmundsson',         pais: 'Suecia',         grupo: 'F' },
  { id: 269, section: 'grupos', tipo: 'defensa',     label: 'Suecia — G. Lagerbielke',         pais: 'Suecia',         grupo: 'F' },
  { id: 270, section: 'grupos', tipo: 'mediocampista',label: 'Suecia — Y. Ayari',              pais: 'Suecia',         grupo: 'F' },
  { id: 271, section: 'grupos', tipo: 'mediocampista',label: 'Suecia — J. Karlström',          pais: 'Suecia',         grupo: 'F' },
  { id: 272, section: 'grupos', tipo: 'mediocampista',label: 'Suecia — L. Bergvall',           pais: 'Suecia',         grupo: 'F' },
  { id: 273, section: 'grupos', tipo: 'mediocampista',label: 'Suecia — H. Larsson',            pais: 'Suecia',         grupo: 'F' },
  { id: 274, section: 'grupos', tipo: 'mediocampista',label: 'Suecia — A. Salétros',           pais: 'Suecia',         grupo: 'F' },
  { id: 275, section: 'grupos', tipo: 'delantero',   label: 'Suecia — A. Isak',                pais: 'Suecia',         grupo: 'F' },
  { id: 276, section: 'grupos', tipo: 'delantero',   label: 'Suecia — A. Bernhardsson',        pais: 'Suecia',         grupo: 'F' },
  { id: 277, section: 'grupos', tipo: 'delantero',   label: 'Suecia — A. Elanga',              pais: 'Suecia',         grupo: 'F' },
  { id: 278, section: 'mvp',    tipo: 'mvp',         label: 'Suecia — MVP Gyökeres',           pais: 'Suecia',         grupo: 'F', isMVP: true, special: true },

  // ── JAPÓN (279-285) ────────────────────────────────────────
  { id: 279, section: 'grupos', tipo: 'seleccion',   label: 'Japón — Selección',               pais: 'Japón',          grupo: 'F' },
  { id: 280, section: 'grupos', tipo: 'arquero',     label: 'Japón — Z. Suzuki',               pais: 'Japón',          grupo: 'F' },
  { id: 281, section: 'grupos', tipo: 'defensa',     label: 'Japón — T. Watanabe',             pais: 'Japón',          grupo: 'F' },
  { id: 282, section: 'grupos', tipo: 'defensa',     label: 'Japón — K. Itakura',              pais: 'Japón',          grupo: 'F' },
  { id: 283, section: 'leyenda',tipo: 'leyenda',     label: 'Japón — Leyenda W. Endo',         pais: 'Japón',          grupo: 'F', isLeyenda: true, special: true },
  { id: 284, section: 'grupos', tipo: 'delantero',   label: 'Japón — T. Minamino',             pais: 'Japón',          grupo: 'F' },
  { id: 285, section: 'mvp',    tipo: 'mvp',         label: 'Japón — MVP T. Kubo',             pais: 'Japón',          grupo: 'F', isMVP: true, special: true },

  // ── TÚNEZ (286-292) ────────────────────────────────────────
  { id: 286, section: 'grupos', tipo: 'seleccion',   label: 'Túnez — Selección',               pais: 'Túnez',          grupo: 'F' },
  { id: 287, section: 'grupos', tipo: 'arquero',     label: 'Túnez — A. Dahmen',               pais: 'Túnez',          grupo: 'F' },
  { id: 288, section: 'grupos', tipo: 'defensa',     label: 'Túnez — M. Talbi',                pais: 'Túnez',          grupo: 'F' },
  { id: 289, section: 'grupos', tipo: 'defensa',     label: 'Túnez — Y. Valery',               pais: 'Túnez',          grupo: 'F' },
  { id: 290, section: 'leyenda',tipo: 'leyenda',     label: 'Túnez — Leyenda A. Ben Slimane',  pais: 'Túnez',          grupo: 'F', isLeyenda: true, special: true },
  { id: 291, section: 'grupos', tipo: 'delantero',   label: 'Túnez — H. Mastouri',             pais: 'Túnez',          grupo: 'F' },
  { id: 292, section: 'mvp',    tipo: 'mvp',         label: 'Túnez — MVP Hannibal',            pais: 'Túnez',          grupo: 'F', isMVP: true, special: true },

  // ── BÉLGICA (293-308) ──────────────────────────────────────
  { id: 293, section: 'grupos', tipo: 'seleccion',   label: 'Bélgica — Selección',             pais: 'Bélgica',        grupo: 'G' },
  { id: 294, section: 'grupos', tipo: 'dt',          label: 'Bélgica — DT R. García',          pais: 'Bélgica',        grupo: 'G' },
  { id: 295, section: 'mvp',    tipo: 'mvp',         label: 'Bélgica — MVP T. Courtois',       pais: 'Bélgica',        grupo: 'G', isMVP: true, special: true },
  { id: 296, section: 'grupos', tipo: 'defensa',     label: 'Bélgica — M. De Cuyper',          pais: 'Bélgica',        grupo: 'G' },
  { id: 297, section: 'grupos', tipo: 'defensa',     label: 'Bélgica — T. Castagne',           pais: 'Bélgica',        grupo: 'G' },
  { id: 298, section: 'grupos', tipo: 'defensa',     label: 'Bélgica — A. Theate',             pais: 'Bélgica',        grupo: 'G' },
  { id: 299, section: 'grupos', tipo: 'defensa',     label: 'Bélgica — Z. Debast',             pais: 'Bélgica',        grupo: 'G' },
  { id: 300, section: 'grupos', tipo: 'mediocampista',label: 'Bélgica — Y. Tielemans',         pais: 'Bélgica',        grupo: 'G' },
  { id: 301, section: 'grupos', tipo: 'mediocampista',label: 'Bélgica — A. Saelemaekers',      pais: 'Bélgica',        grupo: 'G' },
  { id: 302, section: 'leyenda',tipo: 'leyenda',     label: 'Bélgica — Leyenda K. De Bruyne',  pais: 'Bélgica',        grupo: 'G', isLeyenda: true, special: true },
  { id: 303, section: 'grupos', tipo: 'mediocampista',label: 'Bélgica — N. Raskin',            pais: 'Bélgica',        grupo: 'G' },
  { id: 304, section: 'grupos', tipo: 'delantero',   label: 'Bélgica — L. Openda',             pais: 'Bélgica',        grupo: 'G' },
  { id: 305, section: 'grupos', tipo: 'delantero',   label: 'Bélgica — R. Lukaku',             pais: 'Bélgica',        grupo: 'G' },
  { id: 306, section: 'grupos', tipo: 'delantero',   label: 'Bélgica — L. Trossard',           pais: 'Bélgica',        grupo: 'G' },
  { id: 307, section: 'grupos', tipo: 'delantero',   label: 'Bélgica — C. De Ketelaere',       pais: 'Bélgica',        grupo: 'G' },
  { id: 308, section: 'grupos', tipo: 'delantero',   label: 'Bélgica — J. Doku',               pais: 'Bélgica',        grupo: 'G' },

  // ── EGIPTO (309-324) ───────────────────────────────────────
  { id: 309, section: 'grupos', tipo: 'seleccion',   label: 'Egipto — Selección',              pais: 'Egipto',         grupo: 'G' },
  { id: 310, section: 'grupos', tipo: 'dt',          label: 'Egipto — DT H. Hassan',           pais: 'Egipto',         grupo: 'G' },
  { id: 311, section: 'grupos', tipo: 'arquero',     label: 'Egipto — M. El Shenawy',          pais: 'Egipto',         grupo: 'G' },
  { id: 312, section: 'grupos', tipo: 'defensa',     label: 'Egipto — H. Abdelmaguid',         pais: 'Egipto',         grupo: 'G' },
  { id: 313, section: 'grupos', tipo: 'defensa',     label: 'Egipto — M. Hany',                pais: 'Egipto',         grupo: 'G' },
  { id: 314, section: 'grupos', tipo: 'defensa',     label: 'Egipto — R. Rabia',               pais: 'Egipto',         grupo: 'G' },
  { id: 315, section: 'grupos', tipo: 'defensa',     label: 'Egipto — Y. Ibrahim',             pais: 'Egipto',         grupo: 'G' },
  { id: 316, section: 'grupos', tipo: 'mediocampista',label: 'Egipto — A. Fatouh',             pais: 'Egipto',         grupo: 'G' },
  { id: 317, section: 'grupos', tipo: 'mediocampista',label: 'Egipto — E. Ashour',             pais: 'Egipto',         grupo: 'G' },
  { id: 318, section: 'grupos', tipo: 'mediocampista',label: 'Egipto — H. Fathy',              pais: 'Egipto',         grupo: 'G' },
  { id: 319, section: 'grupos', tipo: 'mediocampista',label: 'Egipto — Zizo',                  pais: 'Egipto',         grupo: 'G' },
  { id: 320, section: 'grupos', tipo: 'mediocampista',label: 'Egipto — M. Ateya',              pais: 'Egipto',         grupo: 'G' },
  { id: 321, section: 'grupos', tipo: 'delantero',   label: 'Egipto — M. Mohamed',             pais: 'Egipto',         grupo: 'G' },
  { id: 322, section: 'mvp',    tipo: 'mvp',         label: 'Egipto — MVP O. Marmoush',        pais: 'Egipto',         grupo: 'G', isMVP: true, special: true },
  { id: 323, section: 'grupos', tipo: 'delantero',   label: 'Egipto — Trezeguet',              pais: 'Egipto',         grupo: 'G' },
  { id: 324, section: 'leyenda',tipo: 'leyenda',     label: 'Egipto — Leyenda M. Salah',       pais: 'Egipto',         grupo: 'G', isLeyenda: true, special: true },

  // ── IRÁN (325-331) ─────────────────────────────────────────
  { id: 325, section: 'grupos', tipo: 'seleccion',   label: 'Irán — Selección',                pais: 'Irán',           grupo: 'G' },
  { id: 326, section: 'leyenda',tipo: 'leyenda',     label: 'Irán — Leyenda A. Beiranvand',    pais: 'Irán',           grupo: 'G', isLeyenda: true, special: true },
  { id: 327, section: 'grupos', tipo: 'defensa',     label: 'Irán — S. Khalilzadeh',           pais: 'Irán',           grupo: 'G' },
  { id: 328, section: 'grupos', tipo: 'defensa',     label: 'Irán — M. Mohammadi',             pais: 'Irán',           grupo: 'G' },
  { id: 329, section: 'grupos', tipo: 'mediocampista',label: 'Irán — S. Ezatolahi',            pais: 'Irán',           grupo: 'G' },
  { id: 330, section: 'mvp',    tipo: 'mvp',         label: 'Irán — MVP M. Taremi',            pais: 'Irán',           grupo: 'G', isMVP: true, special: true },
  { id: 331, section: 'grupos', tipo: 'delantero',   label: 'Irán — S. Ghoddos',              pais: 'Irán',           grupo: 'G' },

  // ── NUEVA ZELANDA (332-338) ────────────────────────────────
  { id: 332, section: 'grupos', tipo: 'seleccion',   label: 'Nueva Zelanda — Selección',       pais: 'Nueva Zelanda',  grupo: 'G' },
  { id: 333, section: 'grupos', tipo: 'arquero',     label: 'Nueva Zelanda — M. Crocombe',     pais: 'Nueva Zelanda',  grupo: 'G' },
  { id: 334, section: 'mvp',    tipo: 'mvp',         label: 'Nueva Zelanda — MVP T. Bindon',   pais: 'Nueva Zelanda',  grupo: 'G', isMVP: true, special: true },
  { id: 335, section: 'grupos', tipo: 'defensa',     label: 'Nueva Zelanda — M. Boxall',       pais: 'Nueva Zelanda',  grupo: 'G' },
  { id: 336, section: 'grupos', tipo: 'mediocampista',label: 'Nueva Zelanda — S. Singh',       pais: 'Nueva Zelanda',  grupo: 'G' },
  { id: 337, section: 'grupos', tipo: 'delantero',   label: 'Nueva Zelanda — C. McCowatt',     pais: 'Nueva Zelanda',  grupo: 'G' },
  { id: 338, section: 'leyenda',tipo: 'leyenda',     label: 'Nueva Zelanda — Leyenda C. Wood', pais: 'Nueva Zelanda',  grupo: 'G', isLeyenda: true, special: true },

  // ── ESPAÑA (339-354) ───────────────────────────────────────
  { id: 339, section: 'grupos', tipo: 'seleccion',   label: 'España — Selección',              pais: 'España',         grupo: 'H' },
  { id: 340, section: 'grupos', tipo: 'dt',          label: 'España — DT L. de la Fuente',     pais: 'España',         grupo: 'H' },
  { id: 341, section: 'grupos', tipo: 'arquero',     label: 'España — U. Simón',               pais: 'España',         grupo: 'H' },
  { id: 342, section: 'grupos', tipo: 'defensa',     label: 'España — P. Porro',               pais: 'España',         grupo: 'H' },
  { id: 343, section: 'grupos', tipo: 'defensa',     label: 'España — M. Cucurella',           pais: 'España',         grupo: 'H' },
  { id: 344, section: 'grupos', tipo: 'defensa',     label: 'España — R. Le Normand',          pais: 'España',         grupo: 'H' },
  { id: 345, section: 'leyenda',tipo: 'leyenda',     label: 'España — Leyenda A. Laporte',     pais: 'España',         grupo: 'H', isLeyenda: true, special: true },
  { id: 346, section: 'grupos', tipo: 'mediocampista',label: 'España — F. Ruiz',               pais: 'España',         grupo: 'H' },
  { id: 347, section: 'grupos', tipo: 'mediocampista',label: 'España — Pedri',                 pais: 'España',         grupo: 'H' },
  { id: 348, section: 'grupos', tipo: 'mediocampista',label: 'España — M. Zubimendi',          pais: 'España',         grupo: 'H' },
  { id: 349, section: 'grupos', tipo: 'mediocampista',label: 'España — D. Olmo',               pais: 'España',         grupo: 'H' },
  { id: 350, section: 'grupos', tipo: 'mediocampista',label: 'España — M. Merino',             pais: 'España',         grupo: 'H' },
  { id: 351, section: 'grupos', tipo: 'delantero',   label: 'España — F. Torres',              pais: 'España',         grupo: 'H' },
  { id: 352, section: 'grupos', tipo: 'delantero',   label: 'España — M. Oyarzabal',           pais: 'España',         grupo: 'H' },
  { id: 353, section: 'grupos', tipo: 'delantero',   label: 'España — N. Williams',            pais: 'España',         grupo: 'H' },
  { id: 354, section: 'mvp',    tipo: 'mvp',         label: 'España — MVP L. Yamal',           pais: 'España',         grupo: 'H', isMVP: true, special: true },

  // ── URUGUAY (355-370) ──────────────────────────────────────
  { id: 355, section: 'grupos', tipo: 'seleccion',   label: 'Uruguay — Selección',             pais: 'Uruguay',        grupo: 'H' },
  { id: 356, section: 'grupos', tipo: 'dt',          label: 'Uruguay — DT M. Bielsa',          pais: 'Uruguay',        grupo: 'H' },
  { id: 357, section: 'grupos', tipo: 'arquero',     label: 'Uruguay — S. Rochet',             pais: 'Uruguay',        grupo: 'H' },
  { id: 358, section: 'leyenda',tipo: 'leyenda',     label: 'Uruguay — Leyenda J.M. Giménez',  pais: 'Uruguay',        grupo: 'H', isLeyenda: true, special: true },
  { id: 359, section: 'grupos', tipo: 'defensa',     label: 'Uruguay — R. Araujo',             pais: 'Uruguay',        grupo: 'H' },
  { id: 360, section: 'grupos', tipo: 'defensa',     label: 'Uruguay — M. Ugarte',             pais: 'Uruguay',        grupo: 'H' },
  { id: 361, section: 'grupos', tipo: 'defensa',     label: 'Uruguay — M. Olivera',            pais: 'Uruguay',        grupo: 'H' },
  { id: 362, section: 'grupos', tipo: 'mediocampista',label: 'Uruguay — N. Nández',            pais: 'Uruguay',        grupo: 'H' },
  { id: 363, section: 'mvp',    tipo: 'mvp',         label: 'Uruguay — MVP G. De Arrascaeta',  pais: 'Uruguay',        grupo: 'H', isMVP: true, special: true },
  { id: 364, section: 'grupos', tipo: 'mediocampista',label: 'Uruguay — R. Bentancur',         pais: 'Uruguay',        grupo: 'H' },
  { id: 365, section: 'grupos', tipo: 'mediocampista',label: 'Uruguay — M. Araujo',            pais: 'Uruguay',        grupo: 'H' },
  { id: 366, section: 'grupos', tipo: 'mediocampista',label: 'Uruguay — F. Valverde',          pais: 'Uruguay',        grupo: 'H' },
  { id: 367, section: 'grupos', tipo: 'delantero',   label: 'Uruguay — B. Rodríguez',          pais: 'Uruguay',        grupo: 'H' },
  { id: 368, section: 'grupos', tipo: 'delantero',   label: 'Uruguay — D. Núñez',              pais: 'Uruguay',        grupo: 'H' },
  { id: 369, section: 'grupos', tipo: 'delantero',   label: 'Uruguay — F. Viñas',              pais: 'Uruguay',        grupo: 'H' },
  { id: 370, section: 'grupos', tipo: 'delantero',   label: 'Uruguay — R. Aguirre',            pais: 'Uruguay',        grupo: 'H' },

  // ── CABO VERDE (371-377) ───────────────────────────────────
  { id: 371, section: 'grupos', tipo: 'seleccion',   label: 'Cabo Verde — Selección',          pais: 'Cabo Verde',     grupo: 'H' },
  { id: 372, section: 'leyenda',tipo: 'leyenda',     label: 'Cabo Verde — Leyenda Vozinha',    pais: 'Cabo Verde',     grupo: 'H', isLeyenda: true, special: true },
  { id: 373, section: 'grupos', tipo: 'defensa',     label: 'Cabo Verde — R. Lopes',           pais: 'Cabo Verde',     grupo: 'H' },
  { id: 374, section: 'grupos', tipo: 'defensa',     label: 'Cabo Verde — D. Borges',          pais: 'Cabo Verde',     grupo: 'H' },
  { id: 375, section: 'grupos', tipo: 'mediocampista',label: 'Cabo Verde — K. Lenini',         pais: 'Cabo Verde',     grupo: 'H' },
  { id: 376, section: 'mvp',    tipo: 'mvp',         label: 'Cabo Verde — MVP D. Livramento',  pais: 'Cabo Verde',     grupo: 'H', isMVP: true, special: true },
  { id: 377, section: 'grupos', tipo: 'delantero',   label: 'Cabo Verde — J. Cabral',          pais: 'Cabo Verde',     grupo: 'H' },

  // ── ARABIA SAUDITA (378-384) ───────────────────────────────
  { id: 378, section: 'grupos', tipo: 'seleccion',   label: 'Arabia Saudita — Selección',      pais: 'Arabia Saudita', grupo: 'H' },
  { id: 379, section: 'grupos', tipo: 'arquero',     label: 'Arabia Saudita — N. Al-Aqidi',    pais: 'Arabia Saudita', grupo: 'H' },
  { id: 380, section: 'grupos', tipo: 'defensa',     label: 'Arabia Saudita — N. Boushal',     pais: 'Arabia Saudita', grupo: 'H' },
  { id: 381, section: 'grupos', tipo: 'defensa',     label: 'Arabia Saudita — H. Tambakti',    pais: 'Arabia Saudita', grupo: 'H' },
  { id: 382, section: 'grupos', tipo: 'mediocampista',label: 'Arabia Saudita — A. Al-Khaibari',pais: 'Arabia Saudita', grupo: 'H' },
  { id: 383, section: 'leyenda',tipo: 'leyenda',     label: 'Arabia Saudita — Leyenda S. Al-Dawsari', pais: 'Arabia Saudita', grupo: 'H', isLeyenda: true, special: true },
  { id: 384, section: 'mvp',    tipo: 'mvp',         label: 'Arabia Saudita — MVP F. Al-Buraikan', pais: 'Arabia Saudita', grupo: 'H', isMVP: true, special: true },

  // ── FRANCIA (385-400) ──────────────────────────────────────
  { id: 385, section: 'grupos', tipo: 'seleccion',   label: 'Francia — Selección',             pais: 'Francia',        grupo: 'I' },
  { id: 386, section: 'grupos', tipo: 'dt',          label: 'Francia — DT D. Deschamps',       pais: 'Francia',        grupo: 'I' },
  { id: 387, section: 'grupos', tipo: 'arquero',     label: 'Francia — M. Maignan',            pais: 'Francia',        grupo: 'I' },
  { id: 388, section: 'grupos', tipo: 'defensa',     label: 'Francia — D. Upamecano',          pais: 'Francia',        grupo: 'I' },
  { id: 389, section: 'grupos', tipo: 'defensa',     label: 'Francia — W. Saliba',             pais: 'Francia',        grupo: 'I' },
  { id: 390, section: 'grupos', tipo: 'defensa',     label: 'Francia — J. Koundé',             pais: 'Francia',        grupo: 'I' },
  { id: 391, section: 'grupos', tipo: 'defensa',     label: 'Francia — I. Konaté',             pais: 'Francia',        grupo: 'I' },
  { id: 392, section: 'grupos', tipo: 'mediocampista',label: 'Francia — A. Rabiot',            pais: 'Francia',        grupo: 'I' },
  { id: 393, section: 'leyenda',tipo: 'leyenda',     label: 'Francia — Leyenda N. Kanté',      pais: 'Francia',        grupo: 'I', isLeyenda: true, special: true },
  { id: 394, section: 'grupos', tipo: 'mediocampista',label: 'Francia — A. Tchouaméni',        pais: 'Francia',        grupo: 'I' },
  { id: 395, section: 'grupos', tipo: 'mediocampista',label: 'Francia — T. Hernández',         pais: 'Francia',        grupo: 'I' },
  { id: 396, section: 'grupos', tipo: 'mediocampista',label: 'Francia — M. Olise',             pais: 'Francia',        grupo: 'I' },
  { id: 397, section: 'grupos', tipo: 'delantero',   label: 'Francia — M. Thuram',             pais: 'Francia',        grupo: 'I' },
  { id: 398, section: 'mvp',    tipo: 'mvp',         label: 'Francia — MVP K. Mbappé',         pais: 'Francia',        grupo: 'I', isMVP: true, special: true },
  { id: 399, section: 'grupos', tipo: 'delantero',   label: 'Francia — M. Koné',               pais: 'Francia',        grupo: 'I' },
  { id: 400, section: 'grupos', tipo: 'delantero',   label: 'Francia — O. Dembélé',            pais: 'Francia',        grupo: 'I' },

  // ── NORUEGA (401-416) ──────────────────────────────────────
  { id: 401, section: 'grupos', tipo: 'seleccion',   label: 'Noruega — Selección',             pais: 'Noruega',        grupo: 'I' },
  { id: 402, section: 'grupos', tipo: 'dt',          label: 'Noruega — DT S. Solbakken',       pais: 'Noruega',        grupo: 'I' },
  { id: 403, section: 'leyenda',tipo: 'leyenda',     label: 'Noruega — Leyenda O. Nyland',     pais: 'Noruega',        grupo: 'I', isLeyenda: true, special: true },
  { id: 404, section: 'grupos', tipo: 'defensa',     label: 'Noruega — D. Møller',             pais: 'Noruega',        grupo: 'I' },
  { id: 405, section: 'grupos', tipo: 'defensa',     label: 'Noruega — S. Berge',              pais: 'Noruega',        grupo: 'I' },
  { id: 406, section: 'grupos', tipo: 'defensa',     label: 'Noruega — J. Ryerson',            pais: 'Noruega',        grupo: 'I' },
  { id: 407, section: 'grupos', tipo: 'defensa',     label: 'Noruega — T. Heggem',             pais: 'Noruega',        grupo: 'I' },
  { id: 408, section: 'grupos', tipo: 'mediocampista',label: 'Noruega — P. Berg',              pais: 'Noruega',        grupo: 'I' },
  { id: 409, section: 'grupos', tipo: 'mediocampista',label: 'Noruega — M. Thorsby',           pais: 'Noruega',        grupo: 'I' },
  { id: 410, section: 'grupos', tipo: 'mediocampista',label: 'Noruega — M. Ødegaard',          pais: 'Noruega',        grupo: 'I' },
  { id: 411, section: 'grupos', tipo: 'mediocampista',label: 'Noruega — F. Myhre',             pais: 'Noruega',        grupo: 'I' },
  { id: 412, section: 'grupos', tipo: 'mediocampista',label: 'Noruega — K. Ajer',              pais: 'Noruega',        grupo: 'I' },
  { id: 413, section: 'mvp',    tipo: 'mvp',         label: 'Noruega — MVP E. Haaland',        pais: 'Noruega',        grupo: 'I', isMVP: true, special: true },
  { id: 414, section: 'grupos', tipo: 'delantero',   label: 'Noruega — A. Sørloth',            pais: 'Noruega',        grupo: 'I' },
  { id: 415, section: 'grupos', tipo: 'delantero',   label: 'Noruega — A. Nusa',               pais: 'Noruega',        grupo: 'I' },
  { id: 416, section: 'grupos', tipo: 'delantero',   label: 'Noruega — O. Bobb',               pais: 'Noruega',        grupo: 'I' },

  // ── SENEGAL (417-423) ──────────────────────────────────────
  { id: 417, section: 'grupos', tipo: 'seleccion',   label: 'Senegal — Selección',             pais: 'Senegal',        grupo: 'I' },
  { id: 418, section: 'grupos', tipo: 'arquero',     label: 'Senegal — E. Mendy',              pais: 'Senegal',        grupo: 'I' },
  { id: 419, section: 'grupos', tipo: 'defensa',     label: 'Senegal — K. Koulibaly',          pais: 'Senegal',        grupo: 'I' },
  { id: 420, section: 'grupos', tipo: 'defensa',     label: 'Senegal — M. Niakhaté',           pais: 'Senegal',        grupo: 'I' },
  { id: 421, section: 'grupos', tipo: 'mediocampista',label: 'Senegal — N. Jackson',           pais: 'Senegal',        grupo: 'I' },
  { id: 422, section: 'mvp',    tipo: 'mvp',         label: 'Senegal — MVP K. Diatta',         pais: 'Senegal',        grupo: 'I', isMVP: true, special: true },
  { id: 423, section: 'leyenda',tipo: 'leyenda',     label: 'Senegal — Leyenda S. Mané',       pais: 'Senegal',        grupo: 'I', isLeyenda: true, special: true },

  // ── IRAK (424-430) ─────────────────────────────────────────
  { id: 424, section: 'grupos', tipo: 'seleccion',   label: 'Irak — Selección',                pais: 'Irak',           grupo: 'I' },
  { id: 425, section: 'grupos', tipo: 'arquero',     label: 'Irak — J. Hassan',                pais: 'Irak',           grupo: 'I' },
  { id: 426, section: 'grupos', tipo: 'defensa',     label: 'Irak — M. Doski',                 pais: 'Irak',           grupo: 'I' },
  { id: 427, section: 'grupos', tipo: 'defensa',     label: 'Irak — Z. Tahseen',               pais: 'Irak',           grupo: 'I' },
  { id: 428, section: 'grupos', tipo: 'mediocampista',label: 'Irak — A. Al-Ammari',            pais: 'Irak',           grupo: 'I' },
  { id: 429, section: 'mvp',    tipo: 'mvp',         label: 'Irak — MVP M. Ali',               pais: 'Irak',           grupo: 'I', isMVP: true, special: true },
  { id: 430, section: 'grupos', tipo: 'delantero',   label: 'Irak — A. Hussein',               pais: 'Irak',           grupo: 'I' },

  // ── ARGENTINA (431-446) ────────────────────────────────────
  { id: 431, section: 'grupos', tipo: 'seleccion',   label: 'Argentina — Selección',           pais: 'Argentina',      grupo: 'J' },
  { id: 432, section: 'grupos', tipo: 'dt',          label: 'Argentina — DT L. Scaloni',       pais: 'Argentina',      grupo: 'J' },
  { id: 433, section: 'grupos', tipo: 'arquero',     label: 'Argentina — E. Martínez',         pais: 'Argentina',      grupo: 'J' },
  { id: 434, section: 'grupos', tipo: 'defensa',     label: 'Argentina — C. Romero',           pais: 'Argentina',      grupo: 'J' },
  { id: 435, section: 'grupos', tipo: 'defensa',     label: 'Argentina — N. Otamendi',         pais: 'Argentina',      grupo: 'J' },
  { id: 436, section: 'grupos', tipo: 'defensa',     label: 'Argentina — N. Tagliafico',       pais: 'Argentina',      grupo: 'J' },
  { id: 437, section: 'grupos', tipo: 'defensa',     label: 'Argentina — N. Molina',           pais: 'Argentina',      grupo: 'J' },
  { id: 438, section: 'grupos', tipo: 'mediocampista',label: 'Argentina — R. De Paul',         pais: 'Argentina',      grupo: 'J' },
  { id: 439, section: 'grupos', tipo: 'mediocampista',label: 'Argentina — A. Mac Allister',    pais: 'Argentina',      grupo: 'J' },
  { id: 440, section: 'grupos', tipo: 'mediocampista',label: 'Argentina — E. Fernández',       pais: 'Argentina',      grupo: 'J' },
  { id: 441, section: 'grupos', tipo: 'mediocampista',label: 'Argentina — G. Lo Celso',        pais: 'Argentina',      grupo: 'J' },
  { id: 442, section: 'grupos', tipo: 'delantero',   label: 'Argentina — G. Simeone',          pais: 'Argentina',      grupo: 'J' },
  { id: 443, section: 'leyenda',tipo: 'leyenda',     label: 'Argentina — Leyenda L. Messi',    pais: 'Argentina',      grupo: 'J', isLeyenda: true, special: true },
  { id: 444, section: 'mvp',    tipo: 'mvp',         label: 'Argentina — MVP L. Martínez',     pais: 'Argentina',      grupo: 'J', isMVP: true, special: true },
  { id: 445, section: 'grupos', tipo: 'delantero',   label: 'Argentina — T. Almada',           pais: 'Argentina',      grupo: 'J' },
  { id: 446, section: 'grupos', tipo: 'delantero',   label: 'Argentina — J. Álvarez',          pais: 'Argentina',      grupo: 'J' },

  // ── AUSTRIA (447-453) ──────────────────────────────────────
  { id: 447, section: 'grupos', tipo: 'seleccion',   label: 'Austria — Selección',             pais: 'Austria',        grupo: 'J' },
  { id: 448, section: 'grupos', tipo: 'arquero',     label: 'Austria — A. Schlager',           pais: 'Austria',        grupo: 'J' },
  { id: 449, section: 'grupos', tipo: 'defensa',     label: 'Austria — P. Mwene',              pais: 'Austria',        grupo: 'J' },
  { id: 450, section: 'grupos', tipo: 'defensa',     label: 'Austria — P. Lienhart',           pais: 'Austria',        grupo: 'J' },
  { id: 451, section: 'mvp',    tipo: 'mvp',         label: 'Austria — MVP K. Laimer',         pais: 'Austria',        grupo: 'J', isMVP: true, special: true },
  { id: 452, section: 'grupos', tipo: 'delantero',   label: 'Austria — M. Gregoritsch',        pais: 'Austria',        grupo: 'J' },
  { id: 453, section: 'leyenda',tipo: 'leyenda',     label: 'Austria — Leyenda M. Arnautovic',  pais: 'Austria',        grupo: 'J', isLeyenda: true, special: true },

  // ── JORDANIA (454-460) ─────────────────────────────────────
  { id: 454, section: 'grupos', tipo: 'seleccion',   label: 'Jordania — Selección',            pais: 'Jordania',       grupo: 'J' },
  { id: 455, section: 'leyenda',tipo: 'leyenda',     label: 'Jordania — Leyenda Y. Abulaila',  pais: 'Jordania',       grupo: 'J', isLeyenda: true, special: true },
  { id: 456, section: 'grupos', tipo: 'defensa',     label: 'Jordania — A. Nasib',             pais: 'Jordania',       grupo: 'J' },
  { id: 457, section: 'grupos', tipo: 'defensa',     label: 'Jordania — S. Al-Rosan',          pais: 'Jordania',       grupo: 'J' },
  { id: 458, section: 'grupos', tipo: 'mediocampista',label: 'Jordania — N. Al-Rashdan',       pais: 'Jordania',       grupo: 'J' },
  { id: 459, section: 'grupos', tipo: 'delantero',   label: 'Jordania — M. Al-Mardi',          pais: 'Jordania',       grupo: 'J' },
  { id: 460, section: 'mvp',    tipo: 'mvp',         label: 'Jordania — MVP A. Olwan',         pais: 'Jordania',       grupo: 'J', isMVP: true, special: true },

  // ── ARGELIA (461-476) ──────────────────────────────────────
  { id: 461, section: 'grupos', tipo: 'seleccion',   label: 'Argelia — Selección',             pais: 'Argelia',        grupo: 'J' },
  { id: 462, section: 'grupos', tipo: 'dt',          label: 'Argelia — DT V. Petković',        pais: 'Argelia',        grupo: 'J' },
  { id: 463, section: 'grupos', tipo: 'arquero',     label: 'Argelia — L. Zidane',             pais: 'Argelia',        grupo: 'J' },
  { id: 464, section: 'grupos', tipo: 'defensa',     label: 'Argelia — A. Mandi',              pais: 'Argelia',        grupo: 'J' },
  { id: 465, section: 'grupos', tipo: 'defensa',     label: 'Argelia — R. Bensebaini',         pais: 'Argelia',        grupo: 'J' },
  { id: 466, section: 'grupos', tipo: 'defensa',     label: 'Argelia — R. Belghali',           pais: 'Argelia',        grupo: 'J' },
  { id: 467, section: 'grupos', tipo: 'defensa',     label: 'Argelia — A. Ait-Nouri',          pais: 'Argelia',        grupo: 'J' },
  { id: 468, section: 'grupos', tipo: 'mediocampista',label: 'Argelia — F. Chaïbi',            pais: 'Argelia',        grupo: 'J' },
  { id: 469, section: 'grupos', tipo: 'mediocampista',label: 'Argelia — I. Maza',              pais: 'Argelia',        grupo: 'J' },
  { id: 470, section: 'grupos', tipo: 'mediocampista',label: 'Argelia — I. Bennacer',          pais: 'Argelia',        grupo: 'J' },
  { id: 471, section: 'grupos', tipo: 'mediocampista',label: 'Argelia — H. Boudaoui',          pais: 'Argelia',        grupo: 'J' },
  { id: 472, section: 'grupos', tipo: 'mediocampista',label: 'Argelia — R. Zerrouki',          pais: 'Argelia',        grupo: 'J' },
  { id: 473, section: 'leyenda',tipo: 'leyenda',     label: 'Argelia — Leyenda R. Mahrez',     pais: 'Argelia',        grupo: 'J', isLeyenda: true, special: true },
  { id: 474, section: 'grupos', tipo: 'delantero',   label: 'Argelia — A.H. Moussa',           pais: 'Argelia',        grupo: 'J' },
  { id: 475, section: 'mvp',    tipo: 'mvp',         label: 'Argelia — MVP M. Amoura',         pais: 'Argelia',        grupo: 'J', isMVP: true, special: true },
  { id: 476, section: 'grupos', tipo: 'delantero',   label: 'Argelia — B. Bounedjah',          pais: 'Argelia',        grupo: 'J' },

  // ── PORTUGAL (477-492) ─────────────────────────────────────
  { id: 477, section: 'grupos', tipo: 'seleccion',   label: 'Portugal — Selección',            pais: 'Portugal',       grupo: 'K' },
  { id: 478, section: 'grupos', tipo: 'dt',          label: 'Portugal — DT R. Martínez',       pais: 'Portugal',       grupo: 'K' },
  { id: 479, section: 'grupos', tipo: 'arquero',     label: 'Portugal — D. Costa',             pais: 'Portugal',       grupo: 'K' },
  { id: 480, section: 'grupos', tipo: 'defensa',     label: 'Portugal — R. Dias',              pais: 'Portugal',       grupo: 'K' },
  { id: 481, section: 'grupos', tipo: 'defensa',     label: 'Portugal — N. Mendes',            pais: 'Portugal',       grupo: 'K' },
  { id: 482, section: 'grupos', tipo: 'defensa',     label: 'Portugal — J. Cancelo',           pais: 'Portugal',       grupo: 'K' },
  { id: 483, section: 'grupos', tipo: 'defensa',     label: 'Portugal — D. Dalot',             pais: 'Portugal',       grupo: 'K' },
  { id: 484, section: 'grupos', tipo: 'mediocampista',label: 'Portugal — B. Fernandes',        pais: 'Portugal',       grupo: 'K' },
  { id: 485, section: 'grupos', tipo: 'mediocampista',label: 'Portugal — B. Silva',            pais: 'Portugal',       grupo: 'K' },
  { id: 486, section: 'mvp',    tipo: 'mvp',         label: 'Portugal — MVP Vitinha',          pais: 'Portugal',       grupo: 'K', isMVP: true, special: true },
  { id: 487, section: 'grupos', tipo: 'mediocampista',label: 'Portugal — J. Neves',            pais: 'Portugal',       grupo: 'K' },
  { id: 488, section: 'grupos', tipo: 'mediocampista',label: 'Portugal — R. Neves',            pais: 'Portugal',       grupo: 'K' },
  { id: 489, section: 'grupos', tipo: 'delantero',   label: 'Portugal — P. Neto',              pais: 'Portugal',       grupo: 'K' },
  { id: 490, section: 'leyenda',tipo: 'leyenda',     label: 'Portugal — Leyenda C. Ronaldo',   pais: 'Portugal',       grupo: 'K', isLeyenda: true, special: true },
  { id: 491, section: 'grupos', tipo: 'delantero',   label: 'Portugal — F. Conceição',         pais: 'Portugal',       grupo: 'K' },
  { id: 492, section: 'grupos', tipo: 'delantero',   label: 'Portugal — R. Leão',              pais: 'Portugal',       grupo: 'K' },

  // ── COLOMBIA (493-508) ─────────────────────────────────────
  { id: 493, section: 'grupos', tipo: 'seleccion',   label: 'Colombia — Selección',            pais: 'Colombia',       grupo: 'K' },
  { id: 494, section: 'grupos', tipo: 'dt',          label: 'Colombia — DT N. Lorenzo',        pais: 'Colombia',       grupo: 'K' },
  { id: 495, section: 'grupos', tipo: 'arquero',     label: 'Colombia — C. Vargas',            pais: 'Colombia',       grupo: 'K' },
  { id: 496, section: 'grupos', tipo: 'defensa',     label: 'Colombia — J. Mojica',            pais: 'Colombia',       grupo: 'K' },
  { id: 497, section: 'grupos', tipo: 'defensa',     label: 'Colombia — J. Lucumi',            pais: 'Colombia',       grupo: 'K' },
  { id: 498, section: 'grupos', tipo: 'defensa',     label: 'Colombia — D. Muñoz',             pais: 'Colombia',       grupo: 'K' },
  { id: 499, section: 'grupos', tipo: 'defensa',     label: 'Colombia — D. Sánchez',           pais: 'Colombia',       grupo: 'K' },
  { id: 500, section: 'leyenda',tipo: 'leyenda',     label: 'Colombia — Leyenda J. Rodríguez', pais: 'Colombia',       grupo: 'K', isLeyenda: true, special: true },
  { id: 501, section: 'grupos', tipo: 'mediocampista',label: 'Colombia — R. Ríos',             pais: 'Colombia',       grupo: 'K' },
  { id: 502, section: 'grupos', tipo: 'mediocampista',label: 'Colombia — J. Arias',            pais: 'Colombia',       grupo: 'K' },
  { id: 503, section: 'grupos', tipo: 'mediocampista',label: 'Colombia — J. Lerma',            pais: 'Colombia',       grupo: 'K' },
  { id: 504, section: 'grupos', tipo: 'mediocampista',label: 'Colombia — K. Castaño',          pais: 'Colombia',       grupo: 'K' },
  { id: 505, section: 'grupos', tipo: 'delantero',   label: 'Colombia — J. Durán',             pais: 'Colombia',       grupo: 'K' },
  { id: 506, section: 'grupos', tipo: 'delantero',   label: 'Colombia — J. Córdoba',           pais: 'Colombia',       grupo: 'K' },
  { id: 507, section: 'grupos', tipo: 'delantero',   label: 'Colombia — L. Suárez',            pais: 'Colombia',       grupo: 'K' },
  { id: 508, section: 'mvp',    tipo: 'mvp',         label: 'Colombia — MVP L. Díaz',          pais: 'Colombia',       grupo: 'K', isMVP: true, special: true },

  // ── UZBEKISTÁN (509-515) ───────────────────────────────────
  { id: 509, section: 'grupos', tipo: 'seleccion',   label: 'Uzbekistán — Selección',          pais: 'Uzbekistán',     grupo: 'K' },
  { id: 510, section: 'grupos', tipo: 'arquero',     label: 'Uzbekistán — U. Yusupov',         pais: 'Uzbekistán',     grupo: 'K' },
  { id: 511, section: 'mvp',    tipo: 'mvp',         label: 'Uzbekistán — MVP A. Khusanov',    pais: 'Uzbekistán',     grupo: 'K', isMVP: true, special: true },
  { id: 512, section: 'grupos', tipo: 'defensa',     label: 'Uzbekistán — K. Alizhonov',       pais: 'Uzbekistán',     grupo: 'K' },
  { id: 513, section: 'grupos', tipo: 'mediocampista',label: 'Uzbekistán — O. Khamrobekov',    pais: 'Uzbekistán',     grupo: 'K' },
  { id: 514, section: 'grupos', tipo: 'delantero',   label: 'Uzbekistán — E. Shomurodov',      pais: 'Uzbekistán',     grupo: 'K' },
  { id: 515, section: 'leyenda',tipo: 'leyenda',     label: 'Uzbekistán — Leyenda J. Masharipov', pais: 'Uzbekistán',  grupo: 'K', isLeyenda: true, special: true },

  // ── R.D. CONGO (516-522) ───────────────────────────────────
  { id: 516, section: 'grupos', tipo: 'seleccion',   label: 'R.D. Congo — Selección',          pais: 'R.D. Congo',     grupo: 'K' },
  { id: 517, section: 'grupos', tipo: 'arquero',     label: 'R.D. Congo — L. Mpasi-Nzau',      pais: 'R.D. Congo',     grupo: 'K' },
  { id: 518, section: 'grupos', tipo: 'defensa',     label: 'R.D. Congo — A. Wan-Bissaka',     pais: 'R.D. Congo',     grupo: 'K' },
  { id: 519, section: 'grupos', tipo: 'defensa',     label: 'R.D. Congo — C. Mbemba',          pais: 'R.D. Congo',     grupo: 'K' },
  { id: 520, section: 'grupos', tipo: 'mediocampista',label: 'R.D. Congo — S. Moutoussamy',    pais: 'R.D. Congo',     grupo: 'K' },
  { id: 521, section: 'leyenda',tipo: 'leyenda',     label: 'R.D. Congo — Leyenda C. Bakambu', pais: 'R.D. Congo',     grupo: 'K', isLeyenda: true, special: true },
  { id: 522, section: 'mvp',    tipo: 'mvp',         label: 'R.D. Congo — MVP T. Bongonda',    pais: 'R.D. Congo',     grupo: 'K', isMVP: true, special: true },

  // ── INGLATERRA (523-538) ───────────────────────────────────
  { id: 523, section: 'grupos', tipo: 'seleccion',   label: 'Inglaterra — Selección',          pais: 'Inglaterra',     grupo: 'L' },
  { id: 524, section: 'grupos', tipo: 'dt',          label: 'Inglaterra — DT T. Tuchel',       pais: 'Inglaterra',     grupo: 'L' },
  { id: 525, section: 'grupos', tipo: 'arquero',     label: 'Inglaterra — J. Pickford',        pais: 'Inglaterra',     grupo: 'L' },
  { id: 526, section: 'grupos', tipo: 'defensa',     label: 'Inglaterra — M. Guéhi',           pais: 'Inglaterra',     grupo: 'L' },
  { id: 527, section: 'grupos', tipo: 'defensa',     label: 'Inglaterra — J. Stones',          pais: 'Inglaterra',     grupo: 'L' },
  { id: 528, section: 'grupos', tipo: 'defensa',     label: 'Inglaterra — R. James',           pais: 'Inglaterra',     grupo: 'L' },
  { id: 529, section: 'grupos', tipo: 'defensa',     label: 'Inglaterra — E. Konsa',           pais: 'Inglaterra',     grupo: 'L' },
  { id: 530, section: 'grupos', tipo: 'mediocampista',label: 'Inglaterra — D. Rice',           pais: 'Inglaterra',     grupo: 'L' },
  { id: 531, section: 'grupos', tipo: 'mediocampista',label: 'Inglaterra — C. Palmer',         pais: 'Inglaterra',     grupo: 'L' },
  { id: 532, section: 'grupos', tipo: 'mediocampista',label: 'Inglaterra — J. Bellingham',     pais: 'Inglaterra',     grupo: 'L' },
  { id: 533, section: 'grupos', tipo: 'mediocampista',label: 'Inglaterra — M. Rogers',         pais: 'Inglaterra',     grupo: 'L' },
  { id: 534, section: 'grupos', tipo: 'mediocampista',label: 'Inglaterra — P. Foden',          pais: 'Inglaterra',     grupo: 'L' },
  { id: 535, section: 'grupos', tipo: 'delantero',   label: 'Inglaterra — M. Rashford',        pais: 'Inglaterra',     grupo: 'L' },
  { id: 536, section: 'mvp',    tipo: 'mvp',         label: 'Inglaterra — MVP H. Kane',        pais: 'Inglaterra',     grupo: 'L', isMVP: true, special: true },
  { id: 537, section: 'grupos', tipo: 'delantero',   label: 'Inglaterra — B. Saka',            pais: 'Inglaterra',     grupo: 'L' },
  { id: 538, section: 'grupos', tipo: 'delantero',   label: 'Inglaterra — A. Gordon',          pais: 'Inglaterra',     grupo: 'L' },

  // ── CROACIA (539-554) ──────────────────────────────────────
  { id: 539, section: 'grupos', tipo: 'seleccion',   label: 'Croacia — Selección',             pais: 'Croacia',        grupo: 'L' },
  { id: 540, section: 'grupos', tipo: 'dt',          label: 'Croacia — DT Z. Dalic',           pais: 'Croacia',        grupo: 'L' },
  { id: 541, section: 'mvp',    tipo: 'mvp',         label: 'Croacia — MVP D. Livakovic',      pais: 'Croacia',        grupo: 'L', isMVP: true, special: true },
  { id: 542, section: 'grupos', tipo: 'defensa',     label: 'Croacia — D. Caleta-Car',         pais: 'Croacia',        grupo: 'L' },
  { id: 543, section: 'grupos', tipo: 'defensa',     label: 'Croacia — J. Gvardiol',           pais: 'Croacia',        grupo: 'L' },
  { id: 544, section: 'grupos', tipo: 'defensa',     label: 'Croacia — J. Stanisic',           pais: 'Croacia',        grupo: 'L' },
  { id: 545, section: 'grupos', tipo: 'defensa',     label: 'Croacia — J. Sutalo',             pais: 'Croacia',        grupo: 'L' },
  { id: 546, section: 'leyenda',tipo: 'leyenda',     label: 'Croacia — Leyenda L. Modrić',     pais: 'Croacia',        grupo: 'L', isLeyenda: true, special: true },
  { id: 547, section: 'grupos', tipo: 'mediocampista',label: 'Croacia — M. Pašalić',           pais: 'Croacia',        grupo: 'L' },
  { id: 548, section: 'grupos', tipo: 'mediocampista',label: 'Croacia — P. Sučić',             pais: 'Croacia',        grupo: 'L' },
  { id: 549, section: 'grupos', tipo: 'mediocampista',label: 'Croacia — I. Perišić',           pais: 'Croacia',        grupo: 'L' },
  { id: 550, section: 'grupos', tipo: 'mediocampista',label: 'Croacia — M. Kovacic',           pais: 'Croacia',        grupo: 'L' },
  { id: 551, section: 'grupos', tipo: 'delantero',   label: 'Croacia — N. Vlašić',             pais: 'Croacia',        grupo: 'L' },
  { id: 552, section: 'grupos', tipo: 'delantero',   label: 'Croacia — A. Kramaric',           pais: 'Croacia',        grupo: 'L' },
  { id: 553, section: 'grupos', tipo: 'delantero',   label: 'Croacia — A. Budimir',            pais: 'Croacia',        grupo: 'L' },
  { id: 554, section: 'grupos', tipo: 'delantero',   label: 'Croacia — F. Ivanovic',           pais: 'Croacia',        grupo: 'L' },

  // ── GHANA (555-561) ────────────────────────────────────────
  { id: 555, section: 'grupos', tipo: 'seleccion',   label: 'Ghana — Selección',               pais: 'Ghana',          grupo: 'L' },
  { id: 556, section: 'grupos', tipo: 'arquero',     label: 'Ghana — B. Asare',                pais: 'Ghana',          grupo: 'L' },
  { id: 557, section: 'grupos', tipo: 'defensa',     label: 'Ghana — G. Mensah',               pais: 'Ghana',          grupo: 'L' },
  { id: 558, section: 'grupos', tipo: 'defensa',     label: 'Ghana — A. Djiku',                pais: 'Ghana',          grupo: 'L' },
  { id: 559, section: 'grupos', tipo: 'mediocampista',label: 'Ghana — M. Kudus',               pais: 'Ghana',          grupo: 'L' },
  { id: 560, section: 'mvp',    tipo: 'mvp',         label: 'Ghana — MVP A. Semenyo',          pais: 'Ghana',          grupo: 'L', isMVP: true, special: true },
  { id: 561, section: 'leyenda',tipo: 'leyenda',     label: 'Ghana — Leyenda J. Ayew',         pais: 'Ghana',          grupo: 'L', isLeyenda: true, special: true },

  // ── PANAMÁ (562-568) ───────────────────────────────────────
  { id: 562, section: 'grupos', tipo: 'seleccion',   label: 'Panamá — Selección',              pais: 'Panamá',         grupo: 'L' },
  { id: 563, section: 'grupos', tipo: 'arquero',     label: 'Panamá — O. Mosquera',            pais: 'Panamá',         grupo: 'L' },
  { id: 564, section: 'grupos', tipo: 'defensa',     label: 'Panamá — A. Godoy',               pais: 'Panamá',         grupo: 'L' },
  { id: 565, section: 'leyenda',tipo: 'leyenda',     label: 'Panamá — Leyenda A. Murillo',     pais: 'Panamá',         grupo: 'L', isLeyenda: true, special: true },
  { id: 566, section: 'mvp',    tipo: 'mvp',         label: 'Panamá — MVP A. Carrasquilla',    pais: 'Panamá',         grupo: 'L', isMVP: true, special: true },
  { id: 567, section: 'grupos', tipo: 'delantero',   label: 'Panamá — I. Diaz',                pais: 'Panamá',         grupo: 'L' },
  { id: 568, section: 'grupos', tipo: 'delantero',   label: 'Panamá — J. Fajardo',             pais: 'Panamá',         grupo: 'L' },
]

// ── CAMPEONES (569-580) ───────────────────────────────────────
export const CAMPEONES = [
  { id: 569, section: 'campeones', label: 'Argentina 1978 — Campeón Mundial',  pais: 'Argentina' },
  { id: 570, section: 'campeones', label: 'Italia 1982 — Campeón Mundial',     pais: 'Italia' },
  { id: 571, section: 'campeones', label: 'Argentina 1986 — Campeón Mundial',  pais: 'Argentina' },
  { id: 572, section: 'campeones', label: 'Alemania 1990 — Campeón Mundial',   pais: 'Alemania' },
  { id: 573, section: 'campeones', label: 'Brasil 1994 — Campeón Mundial',     pais: 'Brasil' },
  { id: 574, section: 'campeones', label: 'Francia 1998 — Campeón Mundial',    pais: 'Francia' },
  { id: 575, section: 'campeones', label: 'Brasil 2002 — Campeón Mundial',     pais: 'Brasil' },
  { id: 576, section: 'campeones', label: 'Italia 2006 — Campeón Mundial',     pais: 'Italia' },
  { id: 577, section: 'campeones', label: 'España 2010 — Campeón Mundial',     pais: 'España' },
  { id: 578, section: 'campeones', label: 'Alemania 2014 — Campeón Mundial',   pais: 'Alemania' },
  { id: 579, section: 'campeones', label: 'Francia 2018 — Campeón Mundial',    pais: 'Francia' },
  { id: 580, section: 'campeones', label: 'Argentina 2022 — Campeón Mundial',  pais: 'Argentina' },
]

// ── PRIMERA VEZ EN EL MUNDIAL (581-584) ──────────────────────
export const PRIMERA_VEZ = [
  { id: 581, section: 'debutantes', label: 'Curazao — Primera vez en el Mundial',    pais: 'Curazao' },
  { id: 582, section: 'debutantes', label: 'Uzbekistán — Primera vez en el Mundial', pais: 'Uzbekistán' },
  { id: 583, section: 'debutantes', label: 'Jordania — Primera vez en el Mundial',   pais: 'Jordania' },
  { id: 584, section: 'debutantes', label: 'Cabo Verde — Primera vez en el Mundial', pais: 'Cabo Verde' },
]

// ── ESCUDOS TROQUELADOS (T-1 a T-48) ─────────────────────────
export const TROQUELADOS = [
  { id: 'T-1',  section: 'troquelados', label: 'Escudo Troquelado — México',           special: true },
  { id: 'T-2',  section: 'troquelados', label: 'Escudo Troquelado — Sudáfrica',        special: true },
  { id: 'T-3',  section: 'troquelados', label: 'Escudo Troquelado — Corea del Sur',    special: true },
  { id: 'T-4',  section: 'troquelados', label: 'Escudo Troquelado — Clasificado',      special: true },
  { id: 'T-5',  section: 'troquelados', label: 'Escudo Troquelado — Canadá',           special: true },
  { id: 'T-6',  section: 'troquelados', label: 'Escudo Troquelado — Bosnia y Herz.',   special: true },
  { id: 'T-7',  section: 'troquelados', label: 'Escudo Troquelado — Catar',            special: true },
  { id: 'T-8',  section: 'troquelados', label: 'Escudo Troquelado — Suiza',            special: true },
  { id: 'T-9',  section: 'troquelados', label: 'Escudo Troquelado — Brasil',           special: true },
  { id: 'T-10', section: 'troquelados', label: 'Escudo Troquelado — Marruecos',        special: true },
  { id: 'T-11', section: 'troquelados', label: 'Escudo Troquelado — Haití',            special: true },
  { id: 'T-12', section: 'troquelados', label: 'Escudo Troquelado — Escocia',          special: true },
  { id: 'T-13', section: 'troquelados', label: 'Escudo Troquelado — EE.UU.',           special: true },
  { id: 'T-14', section: 'troquelados', label: 'Escudo Troquelado — Paraguay',         special: true },
  { id: 'T-15', section: 'troquelados', label: 'Escudo Troquelado — Australia',        special: true },
  { id: 'T-16', section: 'troquelados', label: 'Escudo Troquelado — Clasificado',      special: true },
  { id: 'T-17', section: 'troquelados', label: 'Escudo Troquelado — Alemania',         special: true },
  { id: 'T-18', section: 'troquelados', label: 'Escudo Troquelado — Curazao',          special: true },
  { id: 'T-19', section: 'troquelados', label: 'Escudo Troquelado — Costa de Marfil',  special: true },
  { id: 'T-20', section: 'troquelados', label: 'Escudo Troquelado — Ecuador',          special: true },
  { id: 'T-21', section: 'troquelados', label: 'Escudo Troquelado — Países Bajos',     special: true },
  { id: 'T-22', section: 'troquelados', label: 'Escudo Troquelado — Japón',            special: true },
  { id: 'T-23', section: 'troquelados', label: 'Escudo Troquelado — Clasificado',      special: true },
  { id: 'T-24', section: 'troquelados', label: 'Escudo Troquelado — Túnez',            special: true },
  { id: 'T-25', section: 'troquelados', label: 'Escudo Troquelado — Bélgica',          special: true },
  { id: 'T-26', section: 'troquelados', label: 'Escudo Troquelado — Egipto',           special: true },
  { id: 'T-27', section: 'troquelados', label: 'Escudo Troquelado — Irán',             special: true },
  { id: 'T-28', section: 'troquelados', label: 'Escudo Troquelado — Nueva Zelanda',    special: true },
  { id: 'T-29', section: 'troquelados', label: 'Escudo Troquelado — España',           special: true },
  { id: 'T-30', section: 'troquelados', label: 'Escudo Troquelado — Cabo Verde',       special: true },
  { id: 'T-31', section: 'troquelados', label: 'Escudo Troquelado — Arabia Saudita',   special: true },
  { id: 'T-32', section: 'troquelados', label: 'Escudo Troquelado — Uruguay',          special: true },
  { id: 'T-33', section: 'troquelados', label: 'Escudo Troquelado — Francia',          special: true },
  { id: 'T-34', section: 'troquelados', label: 'Escudo Troquelado — Senegal',          special: true },
  { id: 'T-35', section: 'troquelados', label: 'Escudo Troquelado — Noruega',          special: true },
  { id: 'T-36', section: 'troquelados', label: 'Escudo Troquelado — Clasificado',      special: true },
  { id: 'T-37', section: 'troquelados', label: 'Escudo Troquelado — Argentina',        special: true },
  { id: 'T-38', section: 'troquelados', label: 'Escudo Troquelado — Argelia',          special: true },
  { id: 'T-39', section: 'troquelados', label: 'Escudo Troquelado — Austria',          special: true },
  { id: 'T-40', section: 'troquelados', label: 'Escudo Troquelado — Jordania',         special: true },
  { id: 'T-41', section: 'troquelados', label: 'Escudo Troquelado — Colombia',         special: true },
  { id: 'T-42', section: 'troquelados', label: 'Escudo Troquelado — Portugal',         special: true },
  { id: 'T-43', section: 'troquelados', label: 'Escudo Troquelado — Uzbekistán',       special: true },
  { id: 'T-44', section: 'troquelados', label: 'Escudo Troquelado — Clasificado',      special: true },
  { id: 'T-45', section: 'troquelados', label: 'Escudo Troquelado — Inglaterra',       special: true },
  { id: 'T-46', section: 'troquelados', label: 'Escudo Troquelado — Croacia',          special: true },
  { id: 'T-47', section: 'troquelados', label: 'Escudo Troquelado — Panamá',           special: true },
  { id: 'T-48', section: 'troquelados', label: 'Escudo Troquelado — Ghana',            special: true },
]

// ── ÍNDICE COMPLETO EN ORDEN ──────────────────────────────────
export const ALL_STICKERS = [
  ...ESTADIOS,
  ...STICKERS_EQUIPOS,
  ...CAMPEONES,
  ...PRIMERA_VEZ,
  ...TROQUELADOS,
]

export const TOTAL_STICKERS = ALL_STICKERS.length

// Grupos
export const GROUPS = {
  A: ['México', 'Rep. Checa', 'Corea del Sur', 'Sudáfrica'],
  B: ['Canadá', 'Bosnia y Herz.', 'Suiza', 'Catar'],
  C: ['Brasil', 'Marruecos', 'Escocia', 'Haití'],
  D: ['EE.UU.', 'Paraguay', 'Australia', 'Turquía'],
  E: ['Alemania', 'Ecuador', 'Costa de Marfil', 'Curazao'],
  F: ['Países Bajos', 'Suecia', 'Japón', 'Túnez'],
  G: ['Bélgica', 'Egipto', 'Irán', 'Nueva Zelanda'],
  H: ['España', 'Uruguay', 'Cabo Verde', 'Arabia Saudita'],
  I: ['Francia', 'Noruega', 'Senegal', 'Irak'],
  J: ['Argentina', 'Austria', 'Jordania', 'Argelia'],
  K: ['Portugal', 'Colombia', 'Uzbekistán', 'R.D. Congo'],
  L: ['Inglaterra', 'Croacia', 'Ghana', 'Panamá'],
}

// Helpers
export const getStickersBySection = (section) => ALL_STICKERS.filter(s => s.section === section)
export const getStickersByCountry = (pais) => ALL_STICKERS.filter(s => s.pais === pais)
export const getStickersByGroup = (grupo) => ALL_STICKERS.filter(s => s.grupo === grupo)
export const getMVPs = () => ALL_STICKERS.filter(s => s.isMVP)
export const getLeyendas = () => ALL_STICKERS.filter(s => s.isLeyenda)
